"""Phase P0.6.F — Market Perspective™ (Cultural Design Intelligence™).

NOT localization. NOT translation. Cultural REPOSITIONING.

The same project produces different emotional narratives, positioning,
vocabulary and investment framing depending on the target market.

The profile loaded from `market_positioning_profiles` is the source of
truth — it feeds the LLM system prompt with the market's native cultural
context (focus areas, vocabulary, forbidden patterns, system_brief).
"""
import os
import re
import json
import uuid
import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field

from database import db
from core.tenant_context import get_tenant_context

logger = logging.getLogger(__name__)
router = APIRouter(tags=["market-perspectives"])


# ─── Profile loading ─────────────────────────────────────────────────────

def _load_profile(c, locale_code: str) -> Optional[Dict[str, Any]]:
    """Load a locale profile (IT_IT, EN_US, EN_GB, EN_AE, …)."""
    r = (c.table("locale_profiles").select("*")
         .eq("locale_code", locale_code.upper()).limit(1).execute())
    return r.data[0] if r.data else None


# Market-intent-preserving fallback chain — never collapse EN_AE prestige
# into IT_IT craftsmanship etc.
_FALLBACK_CHAIN: Dict[str, List[str]] = {
    "EN_AE": ["EN_GB", "EN_US"],
    "EN_GB": ["EN_US"],
    "EN_US": ["EN_GB"],
    "FR_FR": ["IT_IT", "EN_GB"],
    "DE_DE": ["EN_GB"],
    "ES_ES": ["IT_IT", "EN_GB"],
    "IT_IT": ["EN_GB"],
}


def _resolve_profile(c, locale_code: str) -> Optional[Dict[str, Any]]:
    p = _load_profile(c, locale_code)
    if p:
        return p
    for alt in _FALLBACK_CHAIN.get(locale_code, []):
        alt_p = _load_profile(c, alt)
        if alt_p:
            logger.warning(
                f"perspective locale fallback {locale_code} → {alt} "
                f"(closest cultural register)"
            )
            return alt_p
    return None


def _load_all_profiles(c) -> List[Dict[str, Any]]:
    r = (c.table("locale_profiles")
         .select("locale_code, language, market, display_name, "
                 "emotional_style, focus")
         .order("locale_code").execute())
    return r.data or []


# ─── LLM composer (profile-driven) ───────────────────────────────────────

_PERSPECTIVE_SYSTEM_TEMPLATE = """You are an editorial creative director
repositioning the SAME interior design project for a different locale-native
audience. You are NOT translating. You are NOT softening or escalating tone.
You are NATIVELY recomposing the narrative the way a senior creative
director writing for THAT specific market would write it.

CRITICAL: EN_US, EN_GB and EN_AE all use English, but they are
fundamentally different cultural positionings — never share vocabulary
across them.

═══ LOCALE PROFILE ({locale_code}) ═══
{system_brief}

EMOTIONAL STYLE:      {emotional_style}
LUXURY STYLE:         {luxury_style}
HOSPITALITY STYLE:    {hospitality_style}
EDITORIAL TONE:       {editorial_tone}
CTA STYLE:            {cta_style}
INVESTMENT LANGUAGE:  {investment_language}
ATMOSPHERE LANGUAGE:  {atmosphere_language}

FOCUS AREAS (use these as the conceptual backbone):
  {focus}

VOCABULARY (prefer these terms; never use generic alternatives):
  {vocabulary}

FORBIDDEN PATTERNS (do not use these, ever):
  {forbidden}

POSITIONING EXAMPLES (the tonal register we want):
  {examples}

═══ RULES ═══
• Reposition, do NOT translate. Even if the previous narrative is excellent
  in another locale, REWRITE it natively for this one.
• Write in this locale's language ({language}).
• NEVER mention AI, GPT, "generated by", or any system meta-language.
• Each section: 2–4 sentences of editorial prose. NO bullet points.
• Keep the project's material identity, moodboards and inspirations stable —
  only reposition the COMMUNICATION around them.
• Output: SINGLE valid JSON object, no markdown, no preamble.

JSON SHAPE:
{{
  "headline":             "evocative line, max 14 words, in this locale's language",
  "opening":              "...",
  "strategic_direction":  "...",
  "visual_inspirations":  "...",
  "material_language":    "...",
  "project_vision":       "...",
  "suggested_scope":      "...",
  "investment":           "...",
  "timeline":             "...",
  "signature":            "...",
  "positioning_summary":  "one-line summary of how this locale reads this project"
}}"""


def _build_system_prompt(profile: Dict[str, Any]) -> str:
    return _PERSPECTIVE_SYSTEM_TEMPLATE.format(
        locale_code=profile.get("locale_code", ""),
        system_brief=profile.get("system_brief", ""),
        emotional_style=profile.get("emotional_style", ""),
        luxury_style=profile.get("luxury_style", ""),
        hospitality_style=profile.get("hospitality_style", ""),
        editorial_tone=profile.get("editorial_tone", ""),
        cta_style=profile.get("cta_style", ""),
        investment_language=profile.get("investment_language", ""),
        atmosphere_language=profile.get("atmosphere_language", ""),
        focus=", ".join(profile.get("focus") or []),
        vocabulary=", ".join(profile.get("vocabulary_rules") or []),
        forbidden=", ".join(profile.get("forbidden_patterns") or []),
        examples="\n  ".join(profile.get("positioning_examples") or []),
        language=profile.get("language", "en"),
    )


def _build_user_msg(project_context: Dict[str, Any],
                    existing_sections: Dict[str, Any]) -> str:
    """Feed the LLM the stable project identity + the previous sections
    (as conceptual seed, NOT to translate). The model must REWRITE."""
    seed = {k: v for k, v in (existing_sections or {}).items()
            if k not in ("_locale", "_perspectives", "headline") and isinstance(v, str)}
    return (
        "═══ STABLE PROJECT IDENTITY (do not invent — use these signals) ═══\n"
        f"{json.dumps(project_context, ensure_ascii=False, indent=2, default=str)[:5500]}\n\n"
        "═══ PREVIOUS NARRATIVE (seed — DO NOT TRANSLATE, REPOSITION) ═══\n"
        f"{json.dumps(seed, ensure_ascii=False, indent=2)[:2500]}\n\n"
        "Recompose the editorial proposal natively for the market profile above. "
        "Output JSON only."
    )


def _gather_project_context(c, proposal: Dict[str, Any]) -> Dict[str, Any]:
    """Stable project identity — what does NOT change between markets."""
    pid = proposal["project_id"]
    tid = proposal["tenant_id"]
    ctx: Dict[str, Any] = {}
    try:
        pr = (c.table("projects").select("title, project_type, budget_range, timeline, description, metadata_json")
              .eq("id", pid).eq("tenant_id", tid).limit(1).execute().data or [])
        if pr:
            ctx["project"] = pr[0]
    except Exception:
        pass
    try:
        ins = (c.table("moodboard_candidates").select(
            "title, description, image_url, reference_type, advisor_note"
        ).eq("project_id", pid).eq("tenant_id", tid)
           .order("created_at", desc=True).limit(10).execute().data or [])
        ctx["inspirations"] = ins
    except Exception:
        pass
    try:
        rows = (c.table("material_registry").select(
            "name, category, finish, dominant_color, tags, metadata_json"
        ).eq("tenant_id", tid).eq("status", "active").limit(500).execute().data or [])
        ctx["materials"] = [{
            "name": r.get("name"), "category": r.get("category"),
            "finish": r.get("finish"), "color": r.get("dominant_color"),
            "tags": r.get("tags") or [],
        } for r in rows
            if pid in ((r.get("metadata_json") or {}).get("linked_project_ids") or [])]
    except Exception:
        pass
    return ctx


# ─── Models ──────────────────────────────────────────────────────────────

class SwitchPerspectiveIn(BaseModel):
    locale_code: str = Field(..., min_length=4, max_length=8,
                             description="Composite locale (IT_IT, EN_US, EN_GB, EN_AE, …)")
    set_active:  bool = Field(True, description="Push this perspective live on the proposal")


# ─── Endpoints ───────────────────────────────────────────────────────────

@router.get("/locale-profiles")
def list_locale_profiles(ctx=Depends(get_tenant_context)):
    """All locale profiles available for switching. Used by the UI to render
    the Market Perspective™ pills rail."""
    return {"profiles": _load_all_profiles(db())}


# Legacy alias kept for backward-compatibility of older frontends
@router.get("/market-perspectives/profiles")
def list_profiles_legacy(ctx=Depends(get_tenant_context)):
    return {"profiles": _load_all_profiles(db())}


@router.get("/proposals/{proposal_id}/perspectives")
def list_proposal_perspectives(proposal_id: str, ctx=Depends(get_tenant_context)):
    """All locale versions ever generated for this proposal + which is active."""
    c = db()
    pr = (c.table("proposals").select("id, tenant_id, market, locale_code")
          .eq("id", proposal_id).eq("tenant_id", ctx["tenant_id"])
          .limit(1).execute())
    if not pr.data:
        raise HTTPException(404, "proposal not found")
    rows = (c.table("proposal_market_versions").select(
        "id, locale_code, market_code, locale, headline, positioning_summary, "
        "generated_at, is_active"
    ).eq("proposal_id", proposal_id).eq("tenant_id", ctx["tenant_id"])
       .order("generated_at", desc=True).execute().data or [])
    return {
        "versions":      rows,
        "active_locale": pr.data[0].get("locale_code"),
        "active_market": pr.data[0].get("market"),
    }


@router.post("/proposals/{proposal_id}/perspective", status_code=201)
async def switch_perspective(proposal_id: str, body: SwitchPerspectiveIn,
                             ctx=Depends(get_tenant_context)):
    """Recompose the proposal narrative for `locale_code` using its
    Locale Profile. Saves a new version snapshot. If `set_active=True`
    (default), the proposal's live sections + locale fields are updated."""
    c = db()
    locale_code = body.locale_code.upper()

    # Load proposal
    pr = (c.table("proposals").select("*")
          .eq("id", proposal_id).eq("tenant_id", ctx["tenant_id"]).limit(1).execute())
    if not pr.data:
        raise HTTPException(404, "proposal not found")
    proposal = pr.data[0]

    # Load target locale profile (with market-intent-preserving fallback)
    profile = _resolve_profile(c, locale_code)
    if not profile:
        raise HTTPException(404, f"locale profile {locale_code} not found")
    # If a fallback kicked in, the effective locale is the profile we got.
    locale_code = profile["locale_code"]

    language = profile["language"]
    market   = profile["market"]
    project_ctx = _gather_project_context(c, proposal)
    existing_sections = proposal.get("sections") or {}

    # ── LLM call ────────────────────────────────────────────────────
    new_sections: Dict[str, Any] = {}
    positioning_summary: Optional[str] = None
    used_model = "fallback"
    key = os.environ.get("EMERGENT_LLM_KEY")
    if key:
        try:
            from emergentintegrations.llm.chat import LlmChat, UserMessage  # type: ignore
            chat = (
                LlmChat(
                    api_key=key,
                    session_id=f"persp-{proposal_id}-{locale_code}-{uuid.uuid4().hex[:8]}",
                    system_message=_build_system_prompt(profile),
                )
                .with_model("anthropic", "claude-sonnet-4-5-20250929")
                .with_params(max_tokens=2000)
            )
            raw = await chat.send_message(UserMessage(
                text=_build_user_msg(project_ctx, existing_sections),
            ))
            text = raw if isinstance(raw, str) else getattr(raw, "text", str(raw))
            m = re.search(r"\{[\s\S]*\}", text)
            if m:
                parsed = json.loads(m.group(0))
                # Whitelist editorial section keys
                allowed = {"headline", "opening", "strategic_direction",
                           "visual_inspirations", "material_language",
                           "project_vision", "suggested_scope", "investment",
                           "timeline", "signature"}
                for k, v in parsed.items():
                    if k in allowed and isinstance(v, str) and v.strip():
                        new_sections[k] = v.strip()
                positioning_summary = (parsed.get("positioning_summary") or "").strip() or None
                used_model = "claude-sonnet-4-5"
        except Exception as e:
            logger.warning(f"perspective LLM fallback for {locale_code}: {e}")

    if not new_sections:
        # Minimal fallback: keep existing copy but tag it
        new_sections = {k: v for k, v in existing_sections.items() if isinstance(v, str)}
        new_sections["headline"] = (
            new_sections.get("headline") or "Direzione editoriale"
        )

    # Persist _locale (lowercase language for chrome) so the editor chrome adapts
    new_sections["_locale"] = language
    new_sections["_locale_code"] = locale_code
    headline = new_sections.get("headline") or proposal.get("title") or "—"

    # ── Snapshot in proposal_market_versions ───────────────────────
    snap_id = str(uuid.uuid4())
    iso = datetime.now(timezone.utc).isoformat()
    try:
        if body.set_active:
            c.table("proposal_market_versions").update({"is_active": False}) \
                .eq("proposal_id", proposal_id).eq("tenant_id", ctx["tenant_id"]) \
                .execute()
        existing = (c.table("proposal_market_versions").select("id")
                    .eq("proposal_id", proposal_id).eq("locale_code", locale_code)
                    .eq("tenant_id", ctx["tenant_id"]).limit(1).execute())
        version_payload = {
            "tenant_id":           ctx["tenant_id"],
            "proposal_id":         proposal_id,
            "locale_code":         locale_code,
            "market_code":         market,   # legacy column, kept for analytics
            "locale":              language,
            "sections":            new_sections,
            "headline":            headline,
            "positioning_summary": positioning_summary,
            "generated_by":        ctx["profile_id"],
            "generated_at":        iso,
            "is_active":           body.set_active,
        }
        if existing.data:
            snap_id = existing.data[0]["id"]
            c.table("proposal_market_versions").update(version_payload) \
                .eq("id", snap_id).execute()
        else:
            version_payload["id"] = snap_id
            c.table("proposal_market_versions").insert(version_payload).execute()
    except Exception as e:
        logger.warning(f"perspective snapshot failed: {e}")

    if body.set_active:
        try:
            c.table("proposals").update({
                "sections":    new_sections,
                "market":      market,
                "locale_code": locale_code,
                "title":       headline[:200],
                "updated_at":  iso,
            }).eq("id", proposal_id).eq("tenant_id", ctx["tenant_id"]).execute()
        except Exception as e:
            logger.warning(f"perspective live-update failed: {e}")

    return {
        "ok":                  True,
        "version_id":          snap_id,
        "locale_code":         locale_code,
        "market":              market,
        "language":            language,
        "headline":            headline,
        "positioning_summary": positioning_summary,
        "model_used":          used_model,
    }
