"""Seed the 7 Phase-1 Market Perspective™ profiles.

Run once: `python /app/backend/scripts/seed_market_perspectives.py`

Each profile is the LLM cultural-context source of truth for that market.
Updating a profile changes how Strategic Direction™, Compose Proposal™,
Magazine articles and lead emails are positioned for that audience.
"""
import os
import json
import psycopg2
from dotenv import load_dotenv

load_dotenv("/app/backend/.env")

PROFILES = [
    {
        "market_code": "IT",
        "locale": "it",
        "display_name": "Italia",
        "emotional_tone": "editorial craftsmanship",
        "hospitality_style": "ospitalità domestica, ritmo lento, tavola condivisa",
        "luxury_style": "lusso silenzioso, materia onesta, durata",
        "investment_framing": "valore nel tempo, qualità costruttiva, continuità artigianale",
        "focus": ["materiali", "proporzione", "tempo lungo", "cultura artigianale", "calore spaziale"],
        "vocabulary": ["equilibrio", "materia", "artigianalità", "continuità", "luce naturale",
                       "misura", "atmosfera", "presenza calma", "gesto antico", "registro"],
        "forbidden_patterns": ["lusso ostentato", "stile internazionale generico",
                               "moderno minimal stereotipato", "AI", "powered by"],
        "narrative_examples": [
            "Una conversazione tra materia e luce, calibrata sul ritmo della casa.",
            "Il progetto si misura sul tempo lungo, non sull'effetto immediato.",
        ],
        "system_brief": (
            "You are positioning this project for an Italian audience that "
            "values quiet craftsmanship, material honesty, artisan culture and "
            "continuity with a long Italian design heritage. Speak with editorial "
            "calm. Avoid international-luxury clichés. Prefer concrete material "
            "references and proportion over emotional adjectives. Write natively "
            "in Italian, in a refined editorial register."
        ),
    },
    {
        "market_code": "US",
        "locale": "en",
        "display_name": "United States",
        "emotional_tone": "aspirational lifestyle",
        "hospitality_style": "entertaining flow, social gathering, kitchen as stage",
        "luxury_style": "elevated lifestyle, curated living, statement spaces",
        "investment_framing": "lifestyle return, signature presence, family legacy",
        "focus": ["luxury experience", "entertaining", "elevated living",
                  "personalization", "emotional aspiration"],
        "vocabulary": ["elevated lifestyle", "curated living", "statement kitchen",
                       "entertaining flow", "luxury experience", "signature space",
                       "elevated everyday", "tailored", "destination", "atelier-grade"],
        "forbidden_patterns": ["European-sounding restraint", "understatement clichés",
                               "powered by AI", "GPT", "generated by"],
        "narrative_examples": [
            "A residence designed around the rhythm of how you actually live.",
            "Every surface earns its place in the lifestyle this home invites.",
        ],
        "system_brief": (
            "You are positioning this project for an American audience that values "
            "aspirational lifestyle, entertaining culture, personalization and a "
            "feeling of elevated everyday life. Speak with confident warmth and "
            "lifestyle storytelling. Avoid European-style understatement clichés. "
            "Prefer experience-driven framing over material taxonomy. Write natively "
            "in English, refined editorial register."
        ),
    },
    {
        "market_code": "UAE",
        "locale": "en",
        "display_name": "Emirati Arabi Uniti",
        "emotional_tone": "sensorial prestige",
        "hospitality_style": "majlis hospitality, private reception, layered welcome",
        "luxury_style": "iconic presence, sensorial atmosphere, prestige execution",
        "investment_framing": "iconic asset, prestige positioning, private signature",
        "focus": ["visual impact", "exclusivity", "hospitality", "statement materials",
                  "private luxury"],
        "vocabulary": ["iconic presence", "immersive luxury", "sensorial atmosphere",
                       "prestige execution", "private hospitality", "statement materials",
                       "atelier signature", "exclusive commission", "layered opulence"],
        "forbidden_patterns": ["quiet luxury", "understated", "stripped back",
                               "minimalismo", "powered by AI"],
        "narrative_examples": [
            "A residence that announces its presence through material gravity, not volume.",
            "Each space is a moment of private hospitality, choreographed for the senses.",
        ],
        "system_brief": (
            "You are positioning this project for a Gulf/UAE audience that values "
            "sensorial prestige, iconic presence, layered private hospitality and "
            "statement materials. Speak with confident gravity. Never use 'quiet "
            "luxury' or understatement language. Prefer rich, layered sensorial "
            "descriptions and a sense of commissioned exclusivity. Write natively "
            "in English, refined editorial register."
        ),
    },
    {
        "market_code": "UK",
        "locale": "en",
        "display_name": "Regno Unito",
        "emotional_tone": "restrained editorial luxury",
        "hospitality_style": "quiet hosting, layered domesticity, heritage warmth",
        "luxury_style": "understated luxury, heritage references, timeless composition",
        "investment_framing": "timeless asset, heritage continuity, layered value",
        "focus": ["timeless understatement", "heritage", "atmosphere", "layered sophistication"],
        "vocabulary": ["understated luxury", "refined atmosphere", "quiet statement",
                       "timeless composition", "layered materiality", "considered detailing",
                       "heritage register", "quiet authority"],
        "forbidden_patterns": ["aspirational lifestyle", "statement luxury",
                               "iconic presence", "ostentazione", "AI-generated"],
        "narrative_examples": [
            "A residence written in lower case — confident enough not to raise its voice.",
            "Heritage is treated as a quiet companion, never an instruction.",
        ],
        "system_brief": (
            "You are positioning this project for a UK audience that values "
            "restrained editorial luxury, timeless understatement, heritage "
            "continuity and layered material sophistication. Speak with quiet "
            "authority. Avoid American-style aspirational language and Gulf-style "
            "statement language. Write natively in English, with British editorial "
            "register."
        ),
    },
    {
        "market_code": "FR",
        "locale": "fr",
        "display_name": "France",
        "emotional_tone": "editorial sophistication",
        "hospitality_style": "art de recevoir, hospitalité raffinée, table comme rituel",
        "luxury_style": "élégance discrète, sophistication culturelle, raffinement matériel",
        "investment_framing": "patrimoine, héritage culturel, valeur de continuité",
        "focus": ["élégance subtile", "raffinement culturel", "texture", "luxe retenu"],
        "vocabulary": ["raffinement", "élégance discrète", "sophistication",
                       "lumière douce", "équilibre culturel", "matière noble",
                       "registre éditorial", "tenue", "tension juste"],
        "forbidden_patterns": ["lifestyle aspirationnel", "luxe ostentatoire",
                               "iconic presence", "AI", "généré par"],
        "narrative_examples": [
            "Le projet trouve sa tenue dans la justesse du dessin et la matière retenue.",
            "Une élégance qui se laisse découvrir plutôt qu'annoncer.",
        ],
        "system_brief": (
            "You are positioning this project for a French audience that values "
            "editorial sophistication, subtle elegance, cultural refinement and "
            "restrained luxury. Speak with refined editorial register, almost as "
            "if writing for a French design magazine. Avoid American aspirational "
            "phrasing and Gulf statement phrasing. Write natively in French, in a "
            "soutenu register."
        ),
    },
    {
        "market_code": "DE",
        "locale": "de",
        "display_name": "Deutschland",
        "emotional_tone": "architectural precision",
        "hospitality_style": "klare Gastfreundschaft, ruhige Funktion, redaktioneller Komfort",
        "luxury_style": "architektonische Kohärenz, Materialdisziplin, Detailqualität",
        "investment_framing": "Werterhalt, Ausführungsqualität, Materialinvestition",
        "focus": ["Rigorosität", "Materialdisziplin", "Detaillierung", "Funktion",
                  "Ausführungsqualität"],
        "vocabulary": ["architectural coherence", "material precision", "execution quality",
                       "spatial rigor", "disciplined atmosphere", "präzise Geste",
                       "konstruktive Klarheit", "Materialwahrheit"],
        "forbidden_patterns": ["aspirational lifestyle", "iconic statement",
                               "weiches Gefühl-Vokabular ohne Substanz", "AI-generiert"],
        "narrative_examples": [
            "Das Projekt argumentiert über Konstruktion, nicht über Inszenierung.",
            "Jede Oberfläche trägt Verantwortung gegenüber Funktion und Ausführung.",
        ],
        "system_brief": (
            "You are positioning this project for a German architectural audience "
            "that values rigor, precision, material discipline and execution "
            "quality. Speak as you would in a German architecture magazine "
            "(Bauwelt, AIT). Avoid American lifestyle phrasing and Gulf statement "
            "phrasing. Prefer concrete construction logic over emotional adjectives. "
            "Write natively in German, gehobenes redaktionelles Register."
        ),
    },
    {
        "market_code": "ES",
        "locale": "es",
        "display_name": "España",
        "emotional_tone": "warm experiential Mediterranean",
        "hospitality_style": "sobremesa, espacios sociales, hospitalidad cálida",
        "luxury_style": "luz mediterránea, materiales cálidos, gesto sensorial",
        "investment_framing": "calidad de vida, experiencia compartida, herencia mediterránea",
        "focus": ["espacios sociales", "luz natural", "hospitalidad", "calidez emocional"],
        "vocabulary": ["calidez", "luz natural", "convivencia", "experiencia sensorial",
                       "ritmo mediterráneo", "materia cálida", "atmósfera serena",
                       "gesto poético"],
        "forbidden_patterns": ["lujo frío", "rigor germánico", "AI", "generado por"],
        "narrative_examples": [
            "Una casa pensada para la sobremesa, no para la fotografía.",
            "La luz mediterránea no se imita: se respeta y se construye con ella.",
        ],
        "system_brief": (
            "You are positioning this project for a Spanish audience that values "
            "warm Mediterranean experience, social spaces, natural light and "
            "emotional hospitality. Speak with poetic warmth. Avoid German-style "
            "construction rigor framing and Northern-European restraint clichés. "
            "Write natively in Spanish, culto register."
        ),
    },
]


def main():
    conn = psycopg2.connect(os.environ["DATABASE_URL"])
    conn.autocommit = True
    with conn.cursor() as c:
        for p in PROFILES:
            c.execute("""
                INSERT INTO market_positioning_profiles
                  (market_code, locale, display_name, emotional_tone,
                   hospitality_style, luxury_style, investment_framing,
                   focus, vocabulary, forbidden_patterns, narrative_examples,
                   system_brief)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s::jsonb,%s::jsonb,%s::jsonb,%s::jsonb,%s)
                ON CONFLICT (market_code) DO UPDATE SET
                  locale             = EXCLUDED.locale,
                  display_name       = EXCLUDED.display_name,
                  emotional_tone     = EXCLUDED.emotional_tone,
                  hospitality_style  = EXCLUDED.hospitality_style,
                  luxury_style       = EXCLUDED.luxury_style,
                  investment_framing = EXCLUDED.investment_framing,
                  focus              = EXCLUDED.focus,
                  vocabulary         = EXCLUDED.vocabulary,
                  forbidden_patterns = EXCLUDED.forbidden_patterns,
                  narrative_examples = EXCLUDED.narrative_examples,
                  system_brief       = EXCLUDED.system_brief,
                  updated_at         = NOW();
            """, (
                p["market_code"], p["locale"], p["display_name"],
                p["emotional_tone"], p["hospitality_style"], p["luxury_style"],
                p["investment_framing"],
                json.dumps(p["focus"], ensure_ascii=False),
                json.dumps(p["vocabulary"], ensure_ascii=False),
                json.dumps(p["forbidden_patterns"], ensure_ascii=False),
                json.dumps(p["narrative_examples"], ensure_ascii=False),
                p["system_brief"],
            ))
    print(f"Seeded {len(PROFILES)} market perspective profiles.")
    conn.close()


if __name__ == "__main__":
    main()
