"""
seed_submarkets.py — Market Intelligence Engine™ submarket taxonomy.
═══════════════════════════════════════════════════════════════════════
Seeds geo-cultural submarkets for each macro market with designer-facing
keyword arrays per locale (IT/EN). Two locales per submarket suffice for
Phase 1 — additional locales can be added incrementally.

Cultural fields (each = short keyword array, NEVER technical jargon):
  • editorial_profile        - how the audience reads
  • luxury_profile           - what luxury means here
  • consultation_style       - how they engage advisors
  • visual_behavior          - what images they react to
  • decision_rhythm          - timing of decisions
  • relationship_expectation - what they expect from the studio
  • hospitality_profile      - hospitality codes
  • cta_psychology           - what CTAs feel right
  • visual_rhythm            - pacing of imagery
  • design_culture           - design language affinity
  • seo_behavior             - search intent style
  • publishing_windows       - when content gets attention

Mood: Monocle × AD × FT Weekend.  NEVER Hubspot × Meta Ads.
"""
from __future__ import annotations
import os
import sys
import psycopg2
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from dotenv import load_dotenv
load_dotenv(ROOT / ".env")


# Shorthand helper: build the JSONB dict {it-IT: [...], en-US: [...]}
def K(it_list, en_list):
    return {"it-IT": it_list, "en-US": en_list}


# ═══════════════════════════════════════════════════════════════════════
# SUBMARKETS — handcrafted, ~55 entries.
# ═══════════════════════════════════════════════════════════════════════

SUBMARKETS = [

    # ── USA ──────────────────────────────────────────────────────────
    {
        "code": "usa_nyc", "macro_market_code": "usa_national", "country_code": "US",
        "region_type": "metro", "locale_code": "en-US", "sort_order": 10,
        "display_name": {"it-IT": "New York", "en-US": "New York City"},
        "editorial_profile":   K(["sofisticato","veloce","colto"], ["sophisticated","fast","cultured"]),
        "luxury_profile":      K(["heritage","autorevole","architettonico"], ["heritage","authoritative","architectural"]),
        "consultation_style":  K(["concierge","via referral","24h response"], ["concierge","referral-led","24h response"]),
        "visual_behavior":     K(["prewar","library","skyline"], ["prewar","library","skyline"]),
        "decision_rhythm":     K(["rapido","decisivo"], ["fast","decisive"]),
        "relationship_expectation": K(["principal accessibile","NDA standard"], ["accessible principal","NDA standard"]),
        "hospitality_profile": K(["private dining","art collection"], ["private dining","art collection"]),
        "cta_psychology":      K(["book a private viewing","speak with our principal"], ["book a private viewing","speak with our principal"]),
        "visual_rhythm":       K(["denso","editoriale"], ["dense","editorial"]),
        "design_culture":      K(["AD","Architectural Digest","WSJ Mansion"], ["AD","Architectural Digest","WSJ Mansion"]),
        "seo_behavior":        K(["interior designer NYC","Park Avenue residence"], ["interior designer NYC","Park Avenue residence"]),
        "publishing_windows":  K(["mar-gio mattina ET","domenica sera"], ["Tue-Thu morning ET","Sunday evening"]),
    },
    {
        "code": "usa_miami", "macro_market_code": "usa_south_florida", "country_code": "US",
        "region_type": "metro", "locale_code": "en-US", "sort_order": 20,
        "display_name": {"it-IT": "Miami", "en-US": "Miami"},
        "editorial_profile":   K(["solare","emotivo","resort"], ["sun-driven","emotional","resort"]),
        "luxury_profile":      K(["waterfront","indoor-outdoor","wellness"], ["waterfront","indoor-outdoor","wellness"]),
        "consultation_style":  K(["concierge resort","snowbird tempi"], ["resort concierge","snowbird-paced"]),
        "visual_behavior":     K(["ocean view","palme","travertino"], ["ocean view","palms","travertine"]),
        "decision_rhythm":     K(["stagionale","veloce in season"], ["seasonal","fast in-season"]),
        "relationship_expectation": K(["hospitality estesa","accesso al dock"], ["extended hospitality","dock access"]),
        "hospitality_profile": K(["yacht","outdoor entertaining"], ["yacht","outdoor entertaining"]),
        "cta_psychology":      K(["see waterfront projects","private tour"], ["see waterfront projects","private tour"]),
        "visual_rhythm":       K(["luminoso","scenografico"], ["bright","scenic"]),
        "design_culture":      K(["Ocean Drive","Wynwood","Coconut Grove"], ["Ocean Drive","Wynwood","Coconut Grove"]),
        "seo_behavior":        K(["Miami interior designer","Bal Harbour penthouse"], ["Miami interior designer","Bal Harbour penthouse"]),
        "publishing_windows":  K(["ott-mar prime","gio sera"], ["Oct-Mar peak","Thu evening"]),
    },
    {
        "code": "usa_chicago", "macro_market_code": "usa_national", "country_code": "US",
        "region_type": "metro", "locale_code": "en-US", "sort_order": 30,
        "display_name": {"it-IT": "Chicago", "en-US": "Chicago"},
        "editorial_profile":   K(["concreto","tecnico","misurato"], ["concrete","technical","measured"]),
        "luxury_profile":      K(["heritage industriale","residential comfort"], ["industrial heritage","residential comfort"]),
        "consultation_style":  K(["dettagliato","lunghe sessioni"], ["detailed","long sessions"]),
        "visual_behavior":     K(["materiali","dettagli costruttivi"], ["materials","construction details"]),
        "decision_rhythm":     K(["riflessivo","stagionale"], ["reflective","seasonal"]),
        "relationship_expectation": K(["trasparenza tecnica","follow-up"], ["technical transparency","follow-up"]),
        "hospitality_profile": K(["residential warmth","midwest restraint"], ["residential warmth","midwest restraint"]),
        "cta_psychology":      K(["see our process","detailed estimate"], ["see our process","detailed estimate"]),
        "visual_rhythm":       K(["calmo","architettonico"], ["calm","architectural"]),
        "design_culture":      K(["Mies","Prairie","Lincoln Park"], ["Mies","Prairie","Lincoln Park"]),
        "seo_behavior":        K(["Chicago interior architect","Lincoln Park renovation"], ["Chicago interior architect","Lincoln Park renovation"]),
        "publishing_windows":  K(["apr-ott prime","gio mattina CT"], ["Apr-Oct peak","Thu morning CT"]),
    },
    {
        "code": "usa_los_angeles", "macro_market_code": "usa_west_coast", "country_code": "US",
        "region_type": "metro", "locale_code": "en-US", "sort_order": 40,
        "display_name": {"it-IT": "Los Angeles", "en-US": "Los Angeles"},
        "editorial_profile":   K(["rilassato","sofisticato","biophilic"], ["relaxed","sophisticated","biophilic"]),
        "luxury_profile":      K(["canyon","indoor-outdoor","wellness"], ["canyon","indoor-outdoor","wellness"]),
        "consultation_style":  K(["progettuale","case-study driven"], ["project-led","case-study driven"]),
        "visual_behavior":     K(["vetrate","palette terrose","luce naturale"], ["glazing","earthy palette","natural light"]),
        "decision_rhythm":     K(["esplorativo","scena creativa"], ["exploratory","creative scene"]),
        "relationship_expectation": K(["privacy","sostenibilità reale"], ["privacy","real sustainability"]),
        "hospitality_profile": K(["wellness pool","outdoor screening"], ["wellness pool","outdoor screening"]),
        "cta_psychology":      K(["studio walk-through","view case studies"], ["studio walk-through","view case studies"]),
        "visual_rhythm":       K(["aperto","luminoso"], ["open","sunlit"]),
        "design_culture":      K(["mid-century","case study houses","Schindler"], ["mid-century","case study houses","Schindler"]),
        "seo_behavior":        K(["LA interior designer","Hollywood Hills home"], ["LA interior designer","Hollywood Hills home"]),
        "publishing_windows":  K(["mar-gio mattina PT","weekend lifestyle"], ["Tue-Thu morning PT","weekend lifestyle"]),
    },
    {
        "code": "usa_san_francisco", "macro_market_code": "usa_west_coast", "country_code": "US",
        "region_type": "metro", "locale_code": "en-US", "sort_order": 50,
        "display_name": {"it-IT": "San Francisco", "en-US": "San Francisco"},
        "editorial_profile":   K(["progettuale","tecnologico","misurato"], ["project-led","tech-aware","measured"]),
        "luxury_profile":      K(["wine country","Pacific","wellness"], ["wine country","Pacific","wellness"]),
        "consultation_style":  K(["data-aware","sostenibilità","privacy"], ["data-aware","sustainability","privacy"]),
        "visual_behavior":     K(["Bay views","wine country","modernismo"], ["Bay views","wine country","modernism"]),
        "decision_rhythm":     K(["riflessivo","analitico"], ["reflective","analytical"]),
        "relationship_expectation": K(["NDA tech press","smart home"], ["NDA tech press","smart home"]),
        "hospitality_profile": K(["vineyard estate","Pacific retreat"], ["vineyard estate","Pacific retreat"]),
        "cta_psychology":      K(["book a consultation","see our case studies"], ["book a consultation","see our case studies"]),
        "visual_rhythm":       K(["calmo","contemplativo"], ["calm","contemplative"]),
        "design_culture":      K(["Pac Heights","Sea Ranch","Napa"], ["Pac Heights","Sea Ranch","Napa"]),
        "seo_behavior":        K(["SF interior architect","Napa retreat design"], ["SF interior architect","Napa retreat design"]),
        "publishing_windows":  K(["mar-gio PT","domenica longform"], ["Tue-Thu PT","Sunday longform"]),
    },
    {
        "code": "usa_texas", "macro_market_code": "usa_national", "country_code": "US",
        "region_type": "region", "locale_code": "en-US", "sort_order": 60,
        "display_name": {"it-IT": "Texas", "en-US": "Texas"},
        "editorial_profile":   K(["ampio","caldo","ambizioso"], ["expansive","warm","ambitious"]),
        "luxury_profile":      K(["ranch","oil heritage","cinematic"], ["ranch","oil heritage","cinematic"]),
        "consultation_style":  K(["familiare","ampia scala"], ["familial","large-scale"]),
        "visual_behavior":     K(["paesaggio","outdoor","grandi volumi"], ["landscape","outdoor","grand volumes"]),
        "decision_rhythm":     K(["deciso","ampio budget"], ["decisive","large budget"]),
        "relationship_expectation": K(["personal touch","servizio totale"], ["personal touch","total service"]),
        "hospitality_profile": K(["BBQ formale","ranch entertaining"], ["formal BBQ","ranch entertaining"]),
        "cta_psychology":      K(["come tour the ranch","custom design"], ["come tour the ranch","custom design"]),
        "visual_rhythm":       K(["caldo","aperto"], ["warm","open"]),
        "design_culture":      K(["River Oaks","Highland Park","Hill Country"], ["River Oaks","Highland Park","Hill Country"]),
        "seo_behavior":        K(["Dallas interior designer","Houston home renovation"], ["Dallas interior designer","Houston home renovation"]),
        "publishing_windows":  K(["mer mattina CT","domenica"], ["Wed morning CT","Sunday"]),
    },
    {
        "code": "usa_aspen", "macro_market_code": "usa_national", "country_code": "US",
        "region_type": "region", "locale_code": "en-US", "sort_order": 70,
        "display_name": {"it-IT": "Aspen", "en-US": "Aspen"},
        "editorial_profile":   K(["alpino","raffinato","stagionale"], ["alpine","refined","seasonal"]),
        "luxury_profile":      K(["chalet","ski-in","heritage"], ["chalet","ski-in","heritage"]),
        "consultation_style":  K(["stagionale","white-glove"], ["seasonal","white-glove"]),
        "visual_behavior":     K(["neve","camini","legno scuro"], ["snow","fireplaces","dark wood"]),
        "decision_rhythm":     K(["off-season planning"], ["off-season planning"]),
        "relationship_expectation": K(["concierge globale","trasporto privato"], ["global concierge","private transport"]),
        "hospitality_profile": K(["après-ski","art fair"], ["après-ski","art fair"]),
        "cta_psychology":      K(["private chalet tour"], ["private chalet tour"]),
        "visual_rhythm":       K(["caldo","cinematografico"], ["warm","cinematic"]),
        "design_culture":      K(["Bauer","Aspen Modernism"], ["Bauer","Aspen Modernism"]),
        "seo_behavior":        K(["Aspen interior designer","ski chalet design"], ["Aspen interior designer","ski chalet design"]),
        "publishing_windows":  K(["dic-mar prime","art fair luglio"], ["Dec-Mar peak","July art fair"]),
    },
    {
        "code": "usa_hamptons", "macro_market_code": "usa_east_coast", "country_code": "US",
        "region_type": "region", "locale_code": "en-US", "sort_order": 80,
        "display_name": {"it-IT": "Hamptons", "en-US": "The Hamptons"},
        "editorial_profile":   K(["coastal","heritage","editoriale"], ["coastal","heritage","editorial"]),
        "luxury_profile":      K(["shingle style","ocean","prewar"], ["shingle style","ocean","prewar"]),
        "consultation_style":  K(["off-season planning","summer ready"], ["off-season planning","summer ready"]),
        "visual_behavior":     K(["bianco","tessuti naturali","ocean"], ["white","natural fabrics","ocean"]),
        "decision_rhythm":     K(["pre-Memorial Day","stagionale"], ["pre-Memorial Day","seasonal"]),
        "relationship_expectation": K(["white-glove","NYC-based principal"], ["white-glove","NYC-based principal"]),
        "hospitality_profile": K(["beach club","dinner party"], ["beach club","dinner party"]),
        "cta_psychology":      K(["private viewing","by referral"], ["private viewing","by referral"]),
        "visual_rhythm":       K(["luminoso","editoriale"], ["bright","editorial"]),
        "design_culture":      K(["Southampton","East Hampton","Sag Harbor"], ["Southampton","East Hampton","Sag Harbor"]),
        "seo_behavior":        K(["Hamptons interior designer","beach house renovation"], ["Hamptons interior designer","beach house renovation"]),
        "publishing_windows":  K(["mag-set prime","Labor Day"], ["May-Sep peak","Labor Day"]),
    },
    {
        "code": "usa_scottsdale", "macro_market_code": "usa_national", "country_code": "US",
        "region_type": "region", "locale_code": "en-US", "sort_order": 90,
        "display_name": {"it-IT": "Scottsdale", "en-US": "Scottsdale"},
        "editorial_profile":   K(["desert","luminoso","wellness"], ["desert","sunlit","wellness"]),
        "luxury_profile":      K(["desert retreat","golf","spa"], ["desert retreat","golf","spa"]),
        "consultation_style":  K(["winter season","relocation-aware"], ["winter season","relocation-aware"]),
        "visual_behavior":     K(["adobe","saguaro","tramonti"], ["adobe","saguaro","sunsets"]),
        "decision_rhythm":     K(["nov-apr prime","relocation"], ["Nov-Apr peak","relocation"]),
        "relationship_expectation": K(["climate-aware","wellness"], ["climate-aware","wellness"]),
        "hospitality_profile": K(["resort","desert dinner"], ["resort","desert dinner"]),
        "cta_psychology":      K(["see desert projects","retreat consultation"], ["see desert projects","retreat consultation"]),
        "visual_rhythm":       K(["caldo","aperto"], ["warm","open"]),
        "design_culture":      K(["Wright Taliesin","desert modernism"], ["Wright Taliesin","desert modernism"]),
        "seo_behavior":        K(["Scottsdale interior designer","desert home design"], ["Scottsdale interior designer","desert home design"]),
        "publishing_windows":  K(["nov-mar prime"], ["Nov-Mar peak"]),
    },
    {
        "code": "usa_pacific_northwest", "macro_market_code": "usa_west_coast", "country_code": "US",
        "region_type": "region", "locale_code": "en-US", "sort_order": 100,
        "display_name": {"it-IT": "Pacific Northwest", "en-US": "Pacific Northwest"},
        "editorial_profile":   K(["sostenibile","naturale","calmo"], ["sustainable","natural","calm"]),
        "luxury_profile":      K(["legno","fiordi","biophilic"], ["timber","fjords","biophilic"]),
        "consultation_style":  K(["sostenibilità reale","tech-aware"], ["real sustainability","tech-aware"]),
        "visual_behavior":     K(["legno","Pacific light","pioggia"], ["wood","Pacific light","rain"]),
        "decision_rhythm":     K(["riflessivo","longform"], ["reflective","longform"]),
        "relationship_expectation": K(["certificazioni","local craft"], ["certifications","local craft"]),
        "hospitality_profile": K(["cabin retreat","coffee culture"], ["cabin retreat","coffee culture"]),
        "cta_psychology":      K(["book a studio visit","see our process"], ["book a studio visit","see our process"]),
        "visual_rhythm":       K(["calmo","silenzioso"], ["calm","quiet"]),
        "design_culture":      K(["Pacific Northwest school","Olson Kundig"], ["Pacific Northwest school","Olson Kundig"]),
        "seo_behavior":        K(["Seattle interior designer","Portland sustainable home"], ["Seattle interior designer","Portland sustainable home"]),
        "publishing_windows":  K(["mar-mag prime","longform domenica"], ["Mar-May peak","Sunday longform"]),
    },
    {
        "code": "usa_new_england", "macro_market_code": "usa_east_coast", "country_code": "US",
        "region_type": "region", "locale_code": "en-US", "sort_order": 110,
        "display_name": {"it-IT": "New England", "en-US": "New England"},
        "editorial_profile":   K(["heritage","colto","misurato"], ["heritage","cultured","measured"]),
        "luxury_profile":      K(["coastal heritage","prewar","library"], ["coastal heritage","prewar","library"]),
        "consultation_style":  K(["referral-led","accademico"], ["referral-led","academic"]),
        "visual_behavior":     K(["shingle","clapboard","fall foliage"], ["shingle","clapboard","fall foliage"]),
        "decision_rhythm":     K(["stagionale","longform"], ["seasonal","longform"]),
        "relationship_expectation": K(["heritage rispettato","tradizione"], ["heritage respected","tradition"]),
        "hospitality_profile": K(["country club","sailing"], ["country club","sailing"]),
        "cta_psychology":      K(["enquire","schedule a visit"], ["enquire","schedule a visit"]),
        "visual_rhythm":       K(["calmo","tradizionale"], ["calm","traditional"]),
        "design_culture":      K(["Newport","Nantucket","Cape Cod"], ["Newport","Nantucket","Cape Cod"]),
        "seo_behavior":        K(["Boston interior designer","Newport renovation"], ["Boston interior designer","Newport renovation"]),
        "publishing_windows":  K(["mag-ott prime","Thanksgiving"], ["May-Oct peak","Thanksgiving"]),
    },

    # ── ITALIA (incl. local micro-markets) ────────────────────────────
    {
        "code": "italy_milano", "macro_market_code": "italy", "country_code": "IT",
        "region_type": "metro", "locale_code": "it-IT", "sort_order": 200,
        "display_name": {"it-IT": "Milano", "en-US": "Milan"},
        "editorial_profile":   K(["progettuale","sartoriale","colto"], ["project-led","tailored","cultured"]),
        "luxury_profile":      K(["design week","sartoriale","heritage"], ["design week","tailored","heritage"]),
        "consultation_style":  K(["referenze","appuntamento","studio visit"], ["references","appointment","studio visit"]),
        "visual_behavior":     K(["interni vissuti","materia","luce italiana"], ["lived-in","material","Italian light"]),
        "decision_rhythm":     K(["relazionale","tempo per fiducia"], ["relational","time for trust"]),
        "relationship_expectation": K(["fiducia di lungo termine","mestiere"], ["long-term trust","craft"]),
        "hospitality_profile": K(["aperitivo","atelier dinner"], ["aperitivo","atelier dinner"]),
        "cta_psychology":      K(["prendere appuntamento","visitare lo studio"], ["book a private appointment","visit the studio"]),
        "visual_rhythm":       K(["editoriale","misurato"], ["editorial","measured"]),
        "design_culture":      K(["Brera","Salone","Triennale"], ["Brera","Salone","Triennale"]),
        "seo_behavior":        K(["interior designer Milano","studio architettura Milano"], ["Milan interior designer","Milan design studio"]),
        "publishing_windows":  K(["mar-gio mattina","aprile Salone"], ["Tue-Thu morning","April Salone"]),
    },
    {
        "code": "italy_roma", "macro_market_code": "italy", "country_code": "IT",
        "region_type": "metro", "locale_code": "it-IT", "sort_order": 210,
        "display_name": {"it-IT": "Roma", "en-US": "Rome"},
        "editorial_profile":   K(["classico","colto","ospitale"], ["classical","cultured","hospitable"]),
        "luxury_profile":      K(["palazzo","heritage","scenografico"], ["palazzo","heritage","scenic"]),
        "consultation_style":  K(["personale","tempo","famiglia"], ["personal","time","family"]),
        "visual_behavior":     K(["marmi","stucchi","palazzi"], ["marble","stucco","palazzi"]),
        "decision_rhythm":     K(["riflessivo","famigliare"], ["reflective","familial"]),
        "relationship_expectation": K(["rispetto","tradizione","arte"], ["respect","tradition","art"]),
        "hospitality_profile": K(["pranzo lungo","famiglia allargata"], ["long lunch","extended family"]),
        "cta_psychology":      K(["visitare il palazzo","incontro privato"], ["visit the palazzo","private meeting"]),
        "visual_rhythm":       K(["denso","emotivo"], ["dense","emotional"]),
        "design_culture":      K(["Quirinale","Trastevere","Parioli"], ["Quirinale","Trastevere","Parioli"]),
        "seo_behavior":        K(["interior designer Roma","restauro Roma"], ["Rome interior designer","Rome restoration"]),
        "publishing_windows":  K(["mer pomeriggio","domenica"], ["Wed afternoon","Sunday"]),
    },
    {
        "code": "italy_nord_est", "macro_market_code": "italy", "country_code": "IT",
        "region_type": "region", "locale_code": "it-IT", "sort_order": 220,
        "display_name": {"it-IT": "Nord Est", "en-US": "North East Italy"},
        "editorial_profile":   K(["tecnico","preciso","misurato"], ["technical","precise","measured"]),
        "luxury_profile":      K(["manifattura","heritage industriale","montagne"], ["manufacturing","industrial heritage","mountains"]),
        "consultation_style":  K(["concreto","fatti","tempi certi"], ["concrete","facts","clear timelines"]),
        "visual_behavior":     K(["dettagli costruttivi","manifattura","materiali"], ["construction details","manufacturing","materials"]),
        "decision_rhythm":     K(["pragmatico","veloce"], ["pragmatic","fast"]),
        "relationship_expectation": K(["trasparenza","garanzie","mestiere"], ["transparency","guarantees","craft"]),
        "hospitality_profile": K(["familiare","gastronomia locale"], ["familial","local gastronomy"]),
        "cta_psychology":      K(["sopralluogo","scheda tecnica"], ["site visit","technical sheet"]),
        "visual_rhythm":       K(["sobrio","tecnico"], ["restrained","technical"]),
        "design_culture":      K(["Friuli","Veneto","Brianza esterna"], ["Friuli","Veneto","extended Brianza"]),
        "seo_behavior":        K(["interior designer Verona","studio architettura Padova"], ["Verona interior designer","Padova architecture studio"]),
        "publishing_windows":  K(["mar-mer mattina","novembre"], ["Tue-Wed morning","November"]),
    },
    {
        "code": "italy_verona", "macro_market_code": "italy", "country_code": "IT",
        "region_type": "city", "locale_code": "it-IT", "sort_order": 225,
        "display_name": {"it-IT": "Verona", "en-US": "Verona"},
        "editorial_profile":   K(["sobrio","colto","relazionale"], ["restrained","cultured","relational"]),
        "luxury_profile":      K(["villa veneta","heritage","sartoriale"], ["Veneto villa","heritage","tailored"]),
        "consultation_style":  K(["referral","famigliare","tempi calmi"], ["referral","familial","calm timing"]),
        "visual_behavior":     K(["pietra","intonaci","colline"], ["stone","plaster","hills"]),
        "decision_rhythm":     K(["riflessivo","famigliare"], ["reflective","familial"]),
        "relationship_expectation": K(["discrezione","heritage rispettato"], ["discretion","heritage respected"]),
        "hospitality_profile": K(["vinicola","pranzo conviviale"], ["winery","convivial lunch"]),
        "cta_psychology":      K(["visitare la villa","incontrare il principal"], ["visit the villa","meet the principal"]),
        "visual_rhythm":       K(["editoriale","calmo"], ["editorial","calm"]),
        "design_culture":      K(["Valpolicella","Garda","centro storico"], ["Valpolicella","Garda","old town"]),
        "seo_behavior":        K(["interior designer Verona","villa Garda restauro"], ["Verona interior designer","Lake Garda restoration"]),
        "publishing_windows":  K(["mar mattina","Vinitaly aprile"], ["Tue morning","Vinitaly April"]),
    },
    {
        "code": "italy_lago_di_como", "macro_market_code": "italy", "country_code": "IT",
        "region_type": "region", "locale_code": "it-IT", "sort_order": 230,
        "display_name": {"it-IT": "Lago di Como", "en-US": "Lake Como"},
        "editorial_profile":   K(["scenografico","internazionale","editoriale"], ["scenic","international","editorial"]),
        "luxury_profile":      K(["villa storica","hospitality","cinema"], ["historic villa","hospitality","cinema"]),
        "consultation_style":  K(["multilingue","stagionale","privato"], ["multilingual","seasonal","private"]),
        "visual_behavior":     K(["lago","cipressi","ville classiche"], ["lake","cypress","classical villas"]),
        "decision_rhythm":     K(["stagionale","internazionale"], ["seasonal","international"]),
        "relationship_expectation": K(["NDA celebrity-safe","white-glove"], ["NDA celebrity-safe","white-glove"]),
        "hospitality_profile": K(["boat dinner","villa entertaining"], ["boat dinner","villa entertaining"]),
        "cta_psychology":      K(["private viewing","villa tour"], ["private viewing","villa tour"]),
        "visual_rhythm":       K(["cinematografico","scenografico"], ["cinematic","scenic"]),
        "design_culture":      K(["Bellagio","Tremezzo","Cernobbio"], ["Bellagio","Tremezzo","Cernobbio"]),
        "seo_behavior":        K(["villa Lago Como design","interior designer Como"], ["Lake Como villa design","Como interior designer"]),
        "publishing_windows":  K(["apr-set prime","settembre"], ["Apr-Sep peak","September"]),
    },
    {
        "code": "italy_cortina", "macro_market_code": "italy", "country_code": "IT",
        "region_type": "city", "locale_code": "it-IT", "sort_order": 235,
        "display_name": {"it-IT": "Cortina d'Ampezzo", "en-US": "Cortina d'Ampezzo"},
        "editorial_profile":   K(["alpino","raffinato","stagionale"], ["alpine","refined","seasonal"]),
        "luxury_profile":      K(["chalet dolomitico","ski-in","sartoriale"], ["Dolomite chalet","ski-in","tailored"]),
        "consultation_style":  K(["off-season planning","milanesi commuters"], ["off-season planning","Milan commuters"]),
        "visual_behavior":     K(["legno","loden","Dolomiti"], ["wood","loden","Dolomites"]),
        "decision_rhythm":     K(["pre-stagione","stagionale"], ["pre-season","seasonal"]),
        "relationship_expectation": K(["discrezione","servizio totale"], ["discretion","total service"]),
        "hospitality_profile": K(["chalet dinner","après-ski"], ["chalet dinner","après-ski"]),
        "cta_psychology":      K(["visita allo chalet","appuntamento privato"], ["chalet visit","private appointment"]),
        "visual_rhythm":       K(["caldo","intimo"], ["warm","intimate"]),
        "design_culture":      K(["Dolomiti","sci","artigianato locale"], ["Dolomites","skiing","local craft"]),
        "seo_behavior":        K(["chalet Cortina design","interior designer Dolomiti"], ["Cortina chalet design","Dolomites interior designer"]),
        "publishing_windows":  K(["dic-mar prime","Olimpiadi 2026"], ["Dec-Mar peak","2026 Olympics"]),
    },
    {
        "code": "italy_costa_smeralda", "macro_market_code": "italy", "country_code": "IT",
        "region_type": "coast", "locale_code": "it-IT", "sort_order": 240,
        "display_name": {"it-IT": "Costa Smeralda", "en-US": "Costa Smeralda"},
        "editorial_profile":   K(["mediterraneo","intimo","esclusivo"], ["Mediterranean","intimate","exclusive"]),
        "luxury_profile":      K(["yacht","villa sul mare","hospitality"], ["yacht","seaside villa","hospitality"]),
        "consultation_style":  K(["stagione estiva","internazionale"], ["summer season","international"]),
        "visual_behavior":     K(["mare","ginepri","graniti"], ["sea","juniper","granite"]),
        "decision_rhythm":     K(["pre-stagione","off-season planning"], ["pre-season","off-season planning"]),
        "relationship_expectation": K(["discrezione assoluta","yacht access"], ["absolute discretion","yacht access"]),
        "hospitality_profile": K(["beach dinner","yacht entertaining"], ["beach dinner","yacht entertaining"]),
        "cta_psychology":      K(["private visit","villa walk-through"], ["private visit","villa walk-through"]),
        "visual_rhythm":       K(["luminoso","intimo"], ["bright","intimate"]),
        "design_culture":      K(["Porto Cervo","Liscia di Vacca","Pevero"], ["Porto Cervo","Liscia di Vacca","Pevero"]),
        "seo_behavior":        K(["villa Costa Smeralda design","interior designer Sardegna luxury"], ["Costa Smeralda villa design","Sardinia luxury interior designer"]),
        "publishing_windows":  K(["mag-set prime","off-season nov-feb"], ["May-Sep peak","off-season Nov-Feb"]),
    },
    {
        "code": "italy_forte_dei_marmi", "macro_market_code": "italy", "country_code": "IT",
        "region_type": "city", "locale_code": "it-IT", "sort_order": 245,
        "display_name": {"it-IT": "Forte dei Marmi", "en-US": "Forte dei Marmi"},
        "editorial_profile":   K(["mediterraneo","milanese estivo","sartoriale"], ["Mediterranean","Milanese summer","tailored"]),
        "luxury_profile":      K(["villa bianca","sand","heritage"], ["white villa","sand","heritage"]),
        "consultation_style":  K(["estate","milanesi","famigliare"], ["summer","Milanese","familial"]),
        "visual_behavior":     K(["pinete","bianco","ombrelloni"], ["pine groves","white","beach umbrellas"]),
        "decision_rhythm":     K(["pre-Ferragosto","fine settimana"], ["pre-Ferragosto","weekends"]),
        "relationship_expectation": K(["personalizzazione","tempi rapidi in estate"], ["personalization","fast summer pace"]),
        "hospitality_profile": K(["beach club","cena in pineta"], ["beach club","pine grove dinner"]),
        "cta_psychology":      K(["visita alla villa","appuntamento privato"], ["villa visit","private appointment"]),
        "visual_rhythm":       K(["luminoso","editoriale"], ["bright","editorial"]),
        "design_culture":      K(["Versilia","Pietrasanta","marmo Carrara"], ["Versilia","Pietrasanta","Carrara marble"]),
        "seo_behavior":        K(["villa Forte dei Marmi design","interior designer Versilia"], ["Forte dei Marmi villa design","Versilia interior designer"]),
        "publishing_windows":  K(["giu-ago prime","Ferragosto"], ["Jun-Aug peak","Ferragosto"]),
    },
    {
        "code": "italy_firenze", "macro_market_code": "italy", "country_code": "IT",
        "region_type": "metro", "locale_code": "it-IT", "sort_order": 250,
        "display_name": {"it-IT": "Firenze", "en-US": "Florence"},
        "editorial_profile":   K(["colto","artigianale","editoriale"], ["cultured","artisanal","editorial"]),
        "luxury_profile":      K(["heritage rinascimentale","artigianato","villa toscana"], ["Renaissance heritage","craft","Tuscan villa"]),
        "consultation_style":  K(["accademico","botteghe storiche"], ["academic","historic ateliers"]),
        "visual_behavior":     K(["pietra serena","cotto","oltrarno"], ["pietra serena","terracotta","oltrarno"]),
        "decision_rhythm":     K(["riflessivo","heritage"], ["reflective","heritage"]),
        "relationship_expectation": K(["rispetto del patrimonio","botteghe"], ["heritage respected","ateliers"]),
        "hospitality_profile": K(["pranzo in villa","art collection"], ["villa lunch","art collection"]),
        "cta_psychology":      K(["visita allo studio","incontro nell'atelier"], ["studio visit","atelier meeting"]),
        "visual_rhythm":       K(["editoriale","artigianale"], ["editorial","artisanal"]),
        "design_culture":      K(["Oltrarno","Chianti","Pitti"], ["Oltrarno","Chianti","Pitti"]),
        "seo_behavior":        K(["interior designer Firenze","restauro Toscana"], ["Florence interior designer","Tuscany restoration"]),
        "publishing_windows":  K(["set-ott prime","Pitti Casa"], ["Sep-Oct peak","Pitti Casa"]),
    },
    {
        "code": "italy_sicilia", "macro_market_code": "italy", "country_code": "IT",
        "region_type": "island", "locale_code": "it-IT", "sort_order": 260,
        "display_name": {"it-IT": "Sicilia", "en-US": "Sicily"},
        "editorial_profile":   K(["mediterraneo","barocco","tattile"], ["Mediterranean","baroque","tactile"]),
        "luxury_profile":      K(["palazzo barocco","masseria","scenografico"], ["baroque palazzo","masseria","scenic"]),
        "consultation_style":  K(["personale","tempi famigliari"], ["personal","family pace"]),
        "visual_behavior":     K(["pietra dorata","maiolica","mare"], ["golden stone","maiolica","sea"]),
        "decision_rhythm":     K(["riflessivo","famigliare"], ["reflective","familial"]),
        "relationship_expectation": K(["fiducia personale","local craft"], ["personal trust","local craft"]),
        "hospitality_profile": K(["pranzo lungo","famiglia"], ["long lunch","family"]),
        "cta_psychology":      K(["visita al palazzo","incontro privato"], ["palazzo visit","private meeting"]),
        "visual_rhythm":       K(["denso","emotivo"], ["dense","emotional"]),
        "design_culture":      K(["Noto","Ortigia","Palermo"], ["Noto","Ortigia","Palermo"]),
        "seo_behavior":        K(["interior designer Sicilia","restauro Palermo"], ["Sicily interior designer","Palermo restoration"]),
        "publishing_windows":  K(["mag-ott prime","feste religiose"], ["May-Oct peak","religious holidays"]),
    },
    {
        "code": "italy_napoli", "macro_market_code": "italy", "country_code": "IT",
        "region_type": "metro", "locale_code": "it-IT", "sort_order": 270,
        "display_name": {"it-IT": "Napoli", "en-US": "Naples"},
        "editorial_profile":   K(["barocco","scenografico","sartoriale"], ["baroque","scenic","tailored"]),
        "luxury_profile":      K(["palazzo storico","sartoria","villa vesuviana"], ["historic palazzo","tailoring","Vesuvian villa"]),
        "consultation_style":  K(["personale","famigliare"], ["personal","familial"]),
        "visual_behavior":     K(["maioliche","tufo","mare"], ["maiolica","tuff","sea"]),
        "decision_rhythm":     K(["riflessivo","emotivo"], ["reflective","emotional"]),
        "relationship_expectation": K(["fiducia personale","artigianato"], ["personal trust","craft"]),
        "hospitality_profile": K(["pranzo conviviale","terrazza"], ["convivial lunch","terrace"]),
        "cta_psychology":      K(["incontro privato","visita al palazzo"], ["private meeting","palazzo visit"]),
        "visual_rhythm":       K(["denso","emotivo"], ["dense","emotional"]),
        "design_culture":      K(["Chiaia","Posillipo","Sorrento"], ["Chiaia","Posillipo","Sorrento"]),
        "seo_behavior":        K(["interior designer Napoli","restauro Chiaia"], ["Naples interior designer","Chiaia restoration"]),
        "publishing_windows":  K(["apr-giu prime","Capodanno"], ["Apr-Jun peak","New Year"]),
    },

    # ── FRANCIA ──────────────────────────────────────────────────────
    {
        "code": "france_paris", "macro_market_code": "france_fr_europe", "country_code": "FR",
        "region_type": "metro", "locale_code": "fr-FR", "sort_order": 300,
        "display_name": {"it-IT": "Parigi", "en-US": "Paris"},
        "editorial_profile":   K(["raffinato","discreto","colto"], ["refined","discreet","cultured"]),
        "luxury_profile":      K(["haussmannien","atelier","savoir-faire"], ["Haussmannien","atelier","savoir-faire"]),
        "consultation_style":  K(["referenze","discrezione"], ["references","discretion"]),
        "visual_behavior":     K(["boiserie","marqueterie","Parigi"], ["boiserie","marquetry","Paris"]),
        "decision_rhythm":     K(["riflessivo","accademico"], ["reflective","academic"]),
        "relationship_expectation": K(["discrezione assoluta","atelier"], ["absolute discretion","atelier"]),
        "hospitality_profile": K(["salon dinner","art collection"], ["salon dinner","art collection"]),
        "cta_psychology":      K(["prendre rendez-vous","visite de l'atelier"], ["book an appointment","atelier visit"]),
        "visual_rhythm":       K(["raffinato","misurato"], ["refined","measured"]),
        "design_culture":      K(["Faubourg","Marais","16e"], ["Faubourg","Marais","16e"]),
        "seo_behavior":        K(["architecte d'intérieur Paris","atelier Paris"], ["Paris interior architect","Paris atelier"]),
        "publishing_windows":  K(["mar-gio mattina","gennaio settimana del design"], ["Tue-Thu morning","January design week"]),
    },
    {
        "code": "france_riviera", "macro_market_code": "france_fr_europe", "country_code": "FR",
        "region_type": "coast", "locale_code": "fr-FR", "sort_order": 310,
        "display_name": {"it-IT": "Costa Azzurra", "en-US": "French Riviera"},
        "editorial_profile":   K(["mediterraneo","internazionale","cinematografico"], ["Mediterranean","international","cinematic"]),
        "luxury_profile":      K(["villa belle époque","yacht","heritage"], ["belle époque villa","yacht","heritage"]),
        "consultation_style":  K(["multilingue","stagionale"], ["multilingual","seasonal"]),
        "visual_behavior":     K(["pini marittimi","villa rosa","mare"], ["umbrella pines","pink villa","sea"]),
        "decision_rhythm":     K(["stagionale","prima dell'estate"], ["seasonal","pre-summer"]),
        "relationship_expectation": K(["white-glove","yacht access"], ["white-glove","yacht access"]),
        "hospitality_profile": K(["beach club","villa entertaining"], ["beach club","villa entertaining"]),
        "cta_psychology":      K(["visite privée","tour de la villa"], ["private viewing","villa tour"]),
        "visual_rhythm":       K(["luminoso","cinematografico"], ["bright","cinematic"]),
        "design_culture":      K(["Cap Ferrat","Mougins","Saint-Tropez"], ["Cap Ferrat","Mougins","Saint-Tropez"]),
        "seo_behavior":        K(["architecte Riviera","villa Côte d'Azur design"], ["Riviera architect","Côte d'Azur villa design"]),
        "publishing_windows":  K(["apr-set prime","Cannes maggio"], ["Apr-Sep peak","Cannes May"]),
    },
    {
        "code": "france_lyon", "macro_market_code": "france_fr_europe", "country_code": "FR",
        "region_type": "metro", "locale_code": "fr-FR", "sort_order": 320,
        "display_name": {"it-IT": "Lione", "en-US": "Lyon"},
        "editorial_profile":   K(["gastronomico","colto","sobrio"], ["gastronomic","cultured","restrained"]),
        "luxury_profile":      K(["soyeux","Croix-Rousse","heritage"], ["silk","Croix-Rousse","heritage"]),
        "consultation_style":  K(["famigliare","heritage"], ["familial","heritage"]),
        "visual_behavior":     K(["seta","pietra dorata","Vieux Lyon"], ["silk","golden stone","Vieux Lyon"]),
        "decision_rhythm":     K(["riflessivo","famigliare"], ["reflective","familial"]),
        "relationship_expectation": K(["heritage","gastronomia"], ["heritage","gastronomy"]),
        "hospitality_profile": K(["bouchon dinner"], ["bouchon dinner"]),
        "cta_psychology":      K(["rendez-vous au studio"], ["studio appointment"]),
        "visual_rhythm":       K(["misurato","colto"], ["measured","cultured"]),
        "design_culture":      K(["Soieries","Confluence","Croix-Rousse"], ["Silk heritage","Confluence","Croix-Rousse"]),
        "seo_behavior":        K(["architecte Lyon"], ["Lyon architect"]),
        "publishing_windows":  K(["set-nov","Fête des Lumières"], ["Sep-Nov","Fête des Lumières"]),
    },
    {
        "code": "france_bordeaux", "macro_market_code": "france_fr_europe", "country_code": "FR",
        "region_type": "metro", "locale_code": "fr-FR", "sort_order": 330,
        "display_name": {"it-IT": "Bordeaux", "en-US": "Bordeaux"},
        "editorial_profile":   K(["vinicolo","colto","sobrio"], ["wine country","cultured","restrained"]),
        "luxury_profile":      K(["château","heritage","vigneto"], ["château","heritage","vineyard"]),
        "consultation_style":  K(["heritage","famigliare","internazionale"], ["heritage","familial","international"]),
        "visual_behavior":     K(["pietra dorata","vigne","château"], ["golden stone","vineyards","château"]),
        "decision_rhythm":     K(["riflessivo","stagione vendemmia"], ["reflective","harvest season"]),
        "relationship_expectation": K(["heritage rispettato","internazionale"], ["heritage respected","international"]),
        "hospitality_profile": K(["château dinner","wine tasting"], ["château dinner","wine tasting"]),
        "cta_psychology":      K(["visite du château","rendez-vous privé"], ["château visit","private appointment"]),
        "visual_rhythm":       K(["calmo","editoriale"], ["calm","editorial"]),
        "design_culture":      K(["Médoc","Saint-Émilion","Chartrons"], ["Médoc","Saint-Émilion","Chartrons"]),
        "seo_behavior":        K(["architecte Bordeaux","château renovation"], ["Bordeaux architect","château renovation"]),
        "publishing_windows":  K(["set-ott vendemmia","Vinexpo"], ["Sep-Oct harvest","Vinexpo"]),
    },

    # ── DACH ─────────────────────────────────────────────────────────
    {
        "code": "dach_berlin", "macro_market_code": "dach", "country_code": "DE",
        "region_type": "metro", "locale_code": "de-DE", "sort_order": 400,
        "display_name": {"it-IT": "Berlino", "en-US": "Berlin"},
        "editorial_profile":   K(["minimale","conceptuale","preciso"], ["minimal","conceptual","precise"]),
        "luxury_profile":      K(["altbau","industrial loft","arte"], ["Altbau","industrial loft","art"]),
        "consultation_style":  K(["razionale","tecnico"], ["rational","technical"]),
        "visual_behavior":     K(["altbau","cemento","spazi alti"], ["Altbau","concrete","high ceilings"]),
        "decision_rhythm":     K(["analitico","misurato"], ["analytical","measured"]),
        "relationship_expectation": K(["trasparenza","sostenibilità"], ["transparency","sustainability"]),
        "hospitality_profile": K(["intimo","arte privata"], ["intimate","private art"]),
        "cta_psychology":      K(["Studiobesuch vereinbaren"], ["book a studio visit"]),
        "visual_rhythm":       K(["sobrio","conceptuale"], ["restrained","conceptual"]),
        "design_culture":      K(["Mitte","Kreuzberg","Prenzlauer Berg"], ["Mitte","Kreuzberg","Prenzlauer Berg"]),
        "seo_behavior":        K(["Innenarchitekt Berlin"], ["Berlin interior architect"]),
        "publishing_windows":  K(["mar-gio mattina","Berlin Art Week"], ["Tue-Thu morning","Berlin Art Week"]),
    },
    {
        "code": "dach_munich", "macro_market_code": "dach", "country_code": "DE",
        "region_type": "metro", "locale_code": "de-DE", "sort_order": 410,
        "display_name": {"it-IT": "Monaco di Baviera", "en-US": "Munich"},
        "editorial_profile":   K(["sobrio","heritage","preciso"], ["restrained","heritage","precise"]),
        "luxury_profile":      K(["villa bavarese","heritage","alpino"], ["Bavarian villa","heritage","alpine"]),
        "consultation_style":  K(["formale","fatti","tradizione"], ["formal","facts","tradition"]),
        "visual_behavior":     K(["legno alpino","pietra","Schloss"], ["alpine wood","stone","Schloss"]),
        "decision_rhythm":     K(["pragmatico","veloce"], ["pragmatic","fast"]),
        "relationship_expectation": K(["heritage","garanzie"], ["heritage","guarantees"]),
        "hospitality_profile": K(["Biergarten","villa dinner"], ["Biergarten","villa dinner"]),
        "cta_psychology":      K(["Termin vereinbaren"], ["book an appointment"]),
        "visual_rhythm":       K(["calmo","tradizionale"], ["calm","traditional"]),
        "design_culture":      K(["Schwabing","Bogenhausen","Starnberg"], ["Schwabing","Bogenhausen","Starnberg"]),
        "seo_behavior":        K(["Innenarchitekt München"], ["Munich interior architect"]),
        "publishing_windows":  K(["set-ott prime","Oktoberfest"], ["Sep-Oct peak","Oktoberfest"]),
    },
    {
        "code": "dach_hamburg", "macro_market_code": "dach", "country_code": "DE",
        "region_type": "metro", "locale_code": "de-DE", "sort_order": 420,
        "display_name": {"it-IT": "Amburgo", "en-US": "Hamburg"},
        "editorial_profile":   K(["sobrio","heritage","internazionale"], ["restrained","heritage","international"]),
        "luxury_profile":      K(["Hanseatic","yacht","villa Elbe"], ["Hanseatic","yacht","Elbe villa"]),
        "consultation_style":  K(["formale","internazionale"], ["formal","international"]),
        "visual_behavior":     K(["mattoni rossi","acqua","Elbphilharmonie"], ["red brick","water","Elbphilharmonie"]),
        "decision_rhythm":     K(["misurato","analitico"], ["measured","analytical"]),
        "relationship_expectation": K(["tradizione hanseatica","discrezione"], ["Hanseatic tradition","discretion"]),
        "hospitality_profile": K(["sailing","villa dinner"], ["sailing","villa dinner"]),
        "cta_psychology":      K(["Termin vereinbaren"], ["book an appointment"]),
        "visual_rhythm":       K(["calmo","editoriale"], ["calm","editorial"]),
        "design_culture":      K(["HafenCity","Eppendorf","Blankenese"], ["HafenCity","Eppendorf","Blankenese"]),
        "seo_behavior":        K(["Innenarchitekt Hamburg"], ["Hamburg interior architect"]),
        "publishing_windows":  K(["mar-mag prime"], ["Mar-May peak"]),
    },
    {
        "code": "dach_zurich", "macro_market_code": "dach", "country_code": "CH",
        "region_type": "metro", "locale_code": "de-DE", "sort_order": 430,
        "display_name": {"it-IT": "Zurigo", "en-US": "Zurich"},
        "editorial_profile":   K(["preciso","misurato","sobrio"], ["precise","measured","restrained"]),
        "luxury_profile":      K(["Bahnhofstrasse","lago","heritage"], ["Bahnhofstrasse","lake","heritage"]),
        "consultation_style":  K(["formale","internazionale","discreto"], ["formal","international","discreet"]),
        "visual_behavior":     K(["lago","modernismo svizzero","pulizia"], ["lake","Swiss modernism","cleanliness"]),
        "decision_rhythm":     K(["pragmatico","veloce"], ["pragmatic","fast"]),
        "relationship_expectation": K(["discrezione assoluta","precisione"], ["absolute discretion","precision"]),
        "hospitality_profile": K(["lake villa","art collection"], ["lake villa","art collection"]),
        "cta_psychology":      K(["Termin vereinbaren"], ["book an appointment"]),
        "visual_rhythm":       K(["sobrio","preciso"], ["restrained","precise"]),
        "design_culture":      K(["Goldküste","Zürichberg","Bahnhofstrasse"], ["Goldküste","Zürichberg","Bahnhofstrasse"]),
        "seo_behavior":        K(["Innenarchitekt Zürich"], ["Zurich interior architect"]),
        "publishing_windows":  K(["mar-gio mattina","Art Basel giugno"], ["Tue-Thu morning","Art Basel June"]),
    },
    {
        "code": "dach_vienna", "macro_market_code": "dach", "country_code": "AT",
        "region_type": "metro", "locale_code": "de-DE", "sort_order": 440,
        "display_name": {"it-IT": "Vienna", "en-US": "Vienna"},
        "editorial_profile":   K(["colto","heritage","raffinato"], ["cultured","heritage","refined"]),
        "luxury_profile":      K(["palais","heritage imperiale","arte"], ["palais","imperial heritage","art"]),
        "consultation_style":  K(["formale","accademico"], ["formal","academic"]),
        "visual_behavior":     K(["stucchi","palais","jugendstil"], ["stucco","palais","Jugendstil"]),
        "decision_rhythm":     K(["riflessivo","heritage"], ["reflective","heritage"]),
        "relationship_expectation": K(["heritage rispettato","discrezione"], ["heritage respected","discretion"]),
        "hospitality_profile": K(["palais dinner","opera season"], ["palais dinner","opera season"]),
        "cta_psychology":      K(["Termin vereinbaren"], ["book an appointment"]),
        "visual_rhythm":       K(["denso","editoriale"], ["dense","editorial"]),
        "design_culture":      K(["Innere Stadt","Wiener Werkstätte","Hofburg"], ["Innere Stadt","Wiener Werkstätte","Hofburg"]),
        "seo_behavior":        K(["Innenarchitekt Wien"], ["Vienna interior architect"]),
        "publishing_windows":  K(["ott-dic","stagione opera"], ["Oct-Dec","opera season"]),
    },

    # ── UK ───────────────────────────────────────────────────────────
    {
        "code": "uk_london", "macro_market_code": "uk_ireland", "country_code": "GB",
        "region_type": "metro", "locale_code": "en-GB", "sort_order": 500,
        "display_name": {"it-IT": "Londra", "en-US": "London"},
        "editorial_profile":   K(["heritage","colto","ironico"], ["heritage","cultured","witty"]),
        "luxury_profile":      K(["townhouse","heritage","private members"], ["townhouse","heritage","private members"]),
        "consultation_style":  K(["referenze","members clubs","NDA"], ["references","members clubs","NDA"]),
        "visual_behavior":     K(["townhouse","library","tessuti pesanti"], ["townhouse","library","heavy fabrics"]),
        "decision_rhythm":     K(["misurato","riflessivo"], ["measured","reflective"]),
        "relationship_expectation": K(["discrezione","heritage rispettato"], ["discretion","heritage respected"]),
        "hospitality_profile": K(["members club","townhouse dinner"], ["members club","townhouse dinner"]),
        "cta_psychology":      K(["enquire","visit our atelier"], ["enquire","visit our atelier"]),
        "visual_rhythm":       K(["denso","editoriale"], ["dense","editorial"]),
        "design_culture":      K(["Mayfair","Chelsea","Notting Hill"], ["Mayfair","Chelsea","Notting Hill"]),
        "seo_behavior":        K(["interior designer London","townhouse renovation"], ["interior designer London","townhouse renovation"]),
        "publishing_windows":  K(["mar-mer mattina","Frieze ottobre"], ["Tue-Wed morning","Frieze October"]),
    },
    {
        "code": "uk_scotland", "macro_market_code": "uk_ireland", "country_code": "GB",
        "region_type": "region", "locale_code": "en-GB", "sort_order": 510,
        "display_name": {"it-IT": "Scozia", "en-US": "Scotland"},
        "editorial_profile":   K(["heritage","misurato","tradizione"], ["heritage","measured","tradition"]),
        "luxury_profile":      K(["castello","estate","whisky heritage"], ["castle","estate","whisky heritage"]),
        "consultation_style":  K(["referenze","accademico","tradizione"], ["references","academic","tradition"]),
        "visual_behavior":     K(["tessuti pesanti","torba","heritage"], ["heavy fabrics","peat","heritage"]),
        "decision_rhythm":     K(["riflessivo","stagionale"], ["reflective","seasonal"]),
        "relationship_expectation": K(["heritage rispettato","local craft"], ["heritage respected","local craft"]),
        "hospitality_profile": K(["estate dinner","shooting"], ["estate dinner","shooting"]),
        "cta_psychology":      K(["enquire about the estate"], ["enquire about the estate"]),
        "visual_rhythm":       K(["calmo","tradizionale"], ["calm","traditional"]),
        "design_culture":      K(["Edinburgh","Highlands","Speyside"], ["Edinburgh","Highlands","Speyside"]),
        "seo_behavior":        K(["interior designer Edinburgh","Highland estate design"], ["Edinburgh interior designer","Highland estate design"]),
        "publishing_windows":  K(["apr-ott","stagione caccia"], ["Apr-Oct","shooting season"]),
    },
    {
        "code": "uk_midlands", "macro_market_code": "uk_ireland", "country_code": "GB",
        "region_type": "region", "locale_code": "en-GB", "sort_order": 520,
        "display_name": {"it-IT": "Midlands", "en-US": "The Midlands"},
        "editorial_profile":   K(["heritage","sobrio","famigliare"], ["heritage","restrained","familial"]),
        "luxury_profile":      K(["country house","cotswolds","manor"], ["country house","Cotswolds","manor"]),
        "consultation_style":  K(["referenze","tradizione famigliare"], ["references","family tradition"]),
        "visual_behavior":     K(["pietra Cotswolds","camini","library"], ["Cotswolds stone","fireplaces","library"]),
        "decision_rhythm":     K(["riflessivo","stagionale"], ["reflective","seasonal"]),
        "relationship_expectation": K(["heritage","famigliare","discreto"], ["heritage","familial","discreet"]),
        "hospitality_profile": K(["country house weekend","equestrian"], ["country house weekend","equestrian"]),
        "cta_psychology":      K(["enquire about country house"], ["enquire about country house"]),
        "visual_rhythm":       K(["calmo","editoriale"], ["calm","editorial"]),
        "design_culture":      K(["Cotswolds","Stamford","Rutland"], ["Cotswolds","Stamford","Rutland"]),
        "seo_behavior":        K(["country house interior designer","Cotswolds renovation"], ["country house interior designer","Cotswolds renovation"]),
        "publishing_windows":  K(["mar-set prime","weekend country"], ["Mar-Sep peak","country weekends"]),
    },

    # ── GCC ──────────────────────────────────────────────────────────
    {
        "code": "gcc_dubai", "macro_market_code": "gcc_luxury", "country_code": "AE",
        "region_type": "metro", "locale_code": "en-US", "sort_order": 600,
        "display_name": {"it-IT": "Dubai", "en-US": "Dubai"},
        "editorial_profile":   K(["cerimoniale","scenografico","hospitality"], ["ceremonial","scenic","hospitality"]),
        "luxury_profile":      K(["majlis","marmo statuario","scala monumentale"], ["majlis","statuary marble","monumental scale"]),
        "consultation_style":  K(["white-glove","traduzione araba","NDA"], ["white-glove","Arabic translation","NDA"]),
        "visual_behavior":     K(["marmi","ottoni","illuminazione drammatica"], ["marble","brass","dramatic lighting"]),
        "decision_rhythm":     K(["veloce in season","Ramadan-aware"], ["fast in-season","Ramadan-aware"]),
        "relationship_expectation": K(["servizio totale","VIP-ready"], ["total service","VIP-ready"]),
        "hospitality_profile": K(["majlis","yacht","desert dinner"], ["majlis","yacht","desert dinner"]),
        "cta_psychology":      K(["request a private appointment"], ["request a private appointment"]),
        "visual_rhythm":       K(["scenografico","denso"], ["scenic","dense"]),
        "design_culture":      K(["Palm Jumeirah","Downtown","Emirates Hills"], ["Palm Jumeirah","Downtown","Emirates Hills"]),
        "seo_behavior":        K(["luxury interior designer Dubai"], ["luxury interior designer Dubai"]),
        "publishing_windows":  K(["ott-mar prime","Design Week novembre"], ["Oct-Mar peak","Design Week November"]),
    },
    {
        "code": "gcc_riyadh", "macro_market_code": "gcc_luxury", "country_code": "SA",
        "region_type": "metro", "locale_code": "en-US", "sort_order": 610,
        "display_name": {"it-IT": "Riyadh", "en-US": "Riyadh"},
        "editorial_profile":   K(["cerimoniale","heritage","privato"], ["ceremonial","heritage","private"]),
        "luxury_profile":      K(["palazzo","privacy","majlis"], ["palace","privacy","majlis"]),
        "consultation_style":  K(["formale","traduzione araba","privacy"], ["formal","Arabic translation","privacy"]),
        "visual_behavior":     K(["marmi","arabeschi reinterpretati","scala"], ["marble","reinterpreted arabesques","scale"]),
        "decision_rhythm":     K(["formale","planning lungo"], ["formal","long planning"]),
        "relationship_expectation": K(["servizio totale","discrezione assoluta"], ["total service","absolute discretion"]),
        "hospitality_profile": K(["majlis","cerimoniale"], ["majlis","ceremonial"]),
        "cta_psychology":      K(["request a private appointment"], ["request a private appointment"]),
        "visual_rhythm":       K(["scenografico","cerimoniale"], ["scenic","ceremonial"]),
        "design_culture":      K(["Diplomatic Quarter","Al Olaya","NEOM influence"], ["Diplomatic Quarter","Al Olaya","NEOM influence"]),
        "seo_behavior":        K(["luxury interior designer Riyadh"], ["luxury interior designer Riyadh"]),
        "publishing_windows":  K(["ott-mar prime","post-Ramadan"], ["Oct-Mar peak","post-Ramadan"]),
    },
    {
        "code": "gcc_doha", "macro_market_code": "gcc_luxury", "country_code": "QA",
        "region_type": "metro", "locale_code": "en-US", "sort_order": 620,
        "display_name": {"it-IT": "Doha", "en-US": "Doha"},
        "editorial_profile":   K(["museale","scenografico","cerimoniale"], ["museum-grade","scenic","ceremonial"]),
        "luxury_profile":      K(["heritage","scala monumentale","arte"], ["heritage","monumental scale","art"]),
        "consultation_style":  K(["formale","internazionale","NDA"], ["formal","international","NDA"]),
        "visual_behavior":     K(["marmi","luce desertica","architettura iconica"], ["marble","desert light","iconic architecture"]),
        "decision_rhythm":     K(["pragmatico","planning"], ["pragmatic","planning"]),
        "relationship_expectation": K(["servizio totale","white-glove"], ["total service","white-glove"]),
        "hospitality_profile": K(["majlis","gallery dinner"], ["majlis","gallery dinner"]),
        "cta_psychology":      K(["request a private appointment"], ["request a private appointment"]),
        "visual_rhythm":       K(["scenografico","museale"], ["scenic","museum-grade"]),
        "design_culture":      K(["The Pearl","West Bay","Museum of Islamic Art"], ["The Pearl","West Bay","Museum of Islamic Art"]),
        "seo_behavior":        K(["luxury interior designer Doha"], ["luxury interior designer Doha"]),
        "publishing_windows":  K(["nov-feb prime"], ["Nov-Feb peak"]),
    },
    {
        "code": "gcc_abu_dhabi", "macro_market_code": "gcc_luxury", "country_code": "AE",
        "region_type": "metro", "locale_code": "en-US", "sort_order": 630,
        "display_name": {"it-IT": "Abu Dhabi", "en-US": "Abu Dhabi"},
        "editorial_profile":   K(["istituzionale","heritage","sobrio"], ["institutional","heritage","restrained"]),
        "luxury_profile":      K(["palazzo","mosque heritage","arte"], ["palace","mosque heritage","art"]),
        "consultation_style":  K(["formale","istituzionale","NDA"], ["formal","institutional","NDA"]),
        "visual_behavior":     K(["marmi bianchi","luce","scala monumentale"], ["white marble","light","monumental scale"]),
        "decision_rhythm":     K(["pragmatico","planning lungo"], ["pragmatic","long planning"]),
        "relationship_expectation": K(["servizio totale","heritage rispettato"], ["total service","heritage respected"]),
        "hospitality_profile": K(["majlis","palace dinner"], ["majlis","palace dinner"]),
        "cta_psychology":      K(["request a private appointment"], ["request a private appointment"]),
        "visual_rhythm":       K(["sobrio","monumentale"], ["restrained","monumental"]),
        "design_culture":      K(["Saadiyat","Corniche","Louvre Abu Dhabi"], ["Saadiyat","Corniche","Louvre Abu Dhabi"]),
        "seo_behavior":        K(["luxury interior designer Abu Dhabi"], ["luxury interior designer Abu Dhabi"]),
        "publishing_windows":  K(["nov-feb prime","post-Ramadan"], ["Nov-Feb peak","post-Ramadan"]),
    },

    # ── SPAIN ────────────────────────────────────────────────────────
    {
        "code": "spain_madrid", "macro_market_code": "spain_iberian", "country_code": "ES",
        "region_type": "metro", "locale_code": "es-ES", "sort_order": 700,
        "display_name": {"it-IT": "Madrid", "en-US": "Madrid"},
        "editorial_profile":   K(["colto","sobrio","internazionale"], ["cultured","restrained","international"]),
        "luxury_profile":      K(["palacete","Salamanca","heritage"], ["palacete","Salamanca","heritage"]),
        "consultation_style":  K(["referral","formale","famigliare"], ["referral","formal","familial"]),
        "visual_behavior":     K(["Castellana","palacetes","cortina pesante"], ["Castellana","palacetes","heavy curtains"]),
        "decision_rhythm":     K(["riflessivo","stagionale"], ["reflective","seasonal"]),
        "relationship_expectation": K(["discrezione","heritage"], ["discretion","heritage"]),
        "hospitality_profile": K(["sobremesa","cenas tardías"], ["long lunch","late dinners"]),
        "cta_psychology":      K(["pedir cita","visitar el estudio"], ["book an appointment","visit the studio"]),
        "visual_rhythm":       K(["denso","editoriale"], ["dense","editorial"]),
        "design_culture":      K(["Salamanca","Chamartín","La Moraleja"], ["Salamanca","Chamartín","La Moraleja"]),
        "seo_behavior":        K(["interiorista Madrid","decorador Salamanca"], ["Madrid interior designer","Salamanca decorator"]),
        "publishing_windows":  K(["set-nov","feb-apr"], ["Sep-Nov","Feb-Apr"]),
    },
    {
        "code": "spain_barcelona", "macro_market_code": "spain_iberian", "country_code": "ES",
        "region_type": "metro", "locale_code": "es-ES", "sort_order": 710,
        "display_name": {"it-IT": "Barcellona", "en-US": "Barcelona"},
        "editorial_profile":   K(["modernista","mediterraneo","colto"], ["modernist","Mediterranean","cultured"]),
        "luxury_profile":      K(["modernismo","Eixample","mare"], ["modernism","Eixample","sea"]),
        "consultation_style":  K(["creativo","internazionale"], ["creative","international"]),
        "visual_behavior":     K(["Gaudí","ceramica","luce mediterranea"], ["Gaudí","ceramics","Mediterranean light"]),
        "decision_rhythm":     K(["riflessivo","esplorativo"], ["reflective","exploratory"]),
        "relationship_expectation": K(["creatività","heritage modernista"], ["creativity","modernist heritage"]),
        "hospitality_profile": K(["terraza","beach club"], ["terrace","beach club"]),
        "cta_psychology":      K(["pedir cita","visitar el atelier"], ["book an appointment","visit the atelier"]),
        "visual_rhythm":       K(["luminoso","scenografico"], ["bright","scenic"]),
        "design_culture":      K(["Eixample","Sarrià","Pedralbes"], ["Eixample","Sarrià","Pedralbes"]),
        "seo_behavior":        K(["interiorista Barcelona","reforma Eixample"], ["Barcelona interior designer","Eixample renovation"]),
        "publishing_windows":  K(["mar-giu","set-ott"], ["Mar-Jun","Sep-Oct"]),
    },
    {
        "code": "spain_balearic", "macro_market_code": "spain_iberian", "country_code": "ES",
        "region_type": "island", "locale_code": "es-ES", "sort_order": 720,
        "display_name": {"it-IT": "Baleari", "en-US": "Balearic Islands"},
        "editorial_profile":   K(["mediterraneo","internazionale","biophilic"], ["Mediterranean","international","biophilic"]),
        "luxury_profile":      K(["finca","mare","tramonti"], ["finca","sea","sunsets"]),
        "consultation_style":  K(["stagionale","multilingue"], ["seasonal","multilingual"]),
        "visual_behavior":     K(["bianco","pietra","mare"], ["white","stone","sea"]),
        "decision_rhythm":     K(["pre-stagione","stagionale"], ["pre-season","seasonal"]),
        "relationship_expectation": K(["discrezione","yacht access"], ["discretion","yacht access"]),
        "hospitality_profile": K(["finca dinner","beach club"], ["finca dinner","beach club"]),
        "cta_psychology":      K(["visita privada","finca tour"], ["private visit","finca tour"]),
        "visual_rhythm":       K(["luminoso","intimo"], ["bright","intimate"]),
        "design_culture":      K(["Ibiza","Mallorca","Menorca"], ["Ibiza","Mallorca","Menorca"]),
        "seo_behavior":        K(["finca design Ibiza","interiorista Mallorca"], ["Ibiza finca design","Mallorca interior designer"]),
        "publishing_windows":  K(["mag-set prime","off-season nov-feb"], ["May-Sep peak","off-season Nov-Feb"]),
    },

    # ── LATAM ────────────────────────────────────────────────────────
    {
        "code": "latam_sao_paulo", "macro_market_code": "brazil", "country_code": "BR",
        "region_type": "metro", "locale_code": "en-US", "sort_order": 800,
        "display_name": {"it-IT": "San Paolo", "en-US": "São Paulo"},
        "editorial_profile":   K(["modernista","colto","sensuale"], ["modernist","cultured","sensual"]),
        "luxury_profile":      K(["modernismo paulista","arte","altezza"], ["paulista modernism","art","verticality"]),
        "consultation_style":  K(["referral","colto","accademico"], ["referral","cultured","academic"]),
        "visual_behavior":     K(["cemento","vegetazione","Lina Bo Bardi"], ["concrete","vegetation","Lina Bo Bardi"]),
        "decision_rhythm":     K(["riflessivo","famigliare"], ["reflective","familial"]),
        "relationship_expectation": K(["heritage modernista","arte"], ["modernist heritage","art"]),
        "hospitality_profile": K(["churrasco","art collection dinner"], ["churrasco","art collection dinner"]),
        "cta_psychology":      K(["agendar uma visita","conhecer o portfolio"], ["book a visit","see the portfolio"]),
        "visual_rhythm":       K(["denso","sensuale"], ["dense","sensual"]),
        "design_culture":      K(["Jardins","Vila Madalena","Itaim"], ["Jardins","Vila Madalena","Itaim"]),
        "seo_behavior":        K(["arquiteto São Paulo","apartamento Jardins"], ["São Paulo architect","Jardins apartment"]),
        "publishing_windows":  K(["apr-ott","art week"], ["Apr-Oct","art week"]),
    },
    {
        "code": "latam_rio", "macro_market_code": "brazil", "country_code": "BR",
        "region_type": "metro", "locale_code": "en-US", "sort_order": 810,
        "display_name": {"it-IT": "Rio de Janeiro", "en-US": "Rio de Janeiro"},
        "editorial_profile":   K(["tropicale","sensuale","scenografico"], ["tropical","sensual","scenic"]),
        "luxury_profile":      K(["modernismo carioca","mare","montagne"], ["carioca modernism","sea","mountains"]),
        "consultation_style":  K(["caloroso","famigliare"], ["warm","familial"]),
        "visual_behavior":     K(["vegetazione tropicale","Niemeyer","mare"], ["tropical vegetation","Niemeyer","sea"]),
        "decision_rhythm":     K(["riflessivo","stagionale"], ["reflective","seasonal"]),
        "relationship_expectation": K(["caloroso","famigliare"], ["warm","familial"]),
        "hospitality_profile": K(["churrasco","beach hospitality"], ["churrasco","beach hospitality"]),
        "cta_psychology":      K(["agendar visita"], ["book a visit"]),
        "visual_rhythm":       K(["luminoso","sensuale"], ["bright","sensual"]),
        "design_culture":      K(["Ipanema","Leblon","Jardim Botânico"], ["Ipanema","Leblon","Jardim Botânico"]),
        "seo_behavior":        K(["arquiteto Rio de Janeiro"], ["Rio de Janeiro architect"]),
        "publishing_windows":  K(["mag-ott","off-season carnevale"], ["May-Oct","carnival off-season"]),
    },
    {
        "code": "latam_cdmx", "macro_market_code": "spanish_mexico", "country_code": "MX",
        "region_type": "metro", "locale_code": "es-ES", "sort_order": 820,
        "display_name": {"it-IT": "Città del Messico", "en-US": "Mexico City"},
        "editorial_profile":   K(["coloniale","scultoreo","artigianale"], ["colonial","sculptural","artisanal"]),
        "luxury_profile":      K(["casa Barragán","Polanco","arte"], ["Barragán house","Polanco","art"]),
        "consultation_style":  K(["famigliare","artigianato locale"], ["familial","local craft"]),
        "visual_behavior":     K(["colore","luce dorata","Barragán"], ["color","golden light","Barragán"]),
        "decision_rhythm":     K(["riflessivo","famigliare"], ["reflective","familial"]),
        "relationship_expectation": K(["heritage","artigianato"], ["heritage","craft"]),
        "hospitality_profile": K(["comida larga","patio dinner"], ["long lunch","patio dinner"]),
        "cta_psychology":      K(["agendar cita","conocer el portafolio"], ["book a visit","see the portfolio"]),
        "visual_rhythm":       K(["denso","scenografico"], ["dense","scenic"]),
        "design_culture":      K(["Polanco","Roma Norte","San Ángel"], ["Polanco","Roma Norte","San Ángel"]),
        "seo_behavior":        K(["interiorista CDMX","diseño Polanco"], ["CDMX interior designer","Polanco design"]),
        "publishing_windows":  K(["set-nov","feb-apr"], ["Sep-Nov","Feb-Apr"]),
    },
    {
        "code": "latam_monterrey", "macro_market_code": "spanish_mexico", "country_code": "MX",
        "region_type": "metro", "locale_code": "es-ES", "sort_order": 830,
        "display_name": {"it-IT": "Monterrey", "en-US": "Monterrey"},
        "editorial_profile":   K(["industriale","famigliare","scenografico"], ["industrial","familial","scenic"]),
        "luxury_profile":      K(["heritage industriale","Sierra Madre","scala"], ["industrial heritage","Sierra Madre","scale"]),
        "consultation_style":  K(["famigliare","internazionale","pragmatico"], ["familial","international","pragmatic"]),
        "visual_behavior":     K(["montagne","industrial materials","scala"], ["mountains","industrial materials","scale"]),
        "decision_rhythm":     K(["pragmatico","veloce"], ["pragmatic","fast"]),
        "relationship_expectation": K(["famigliare","servizio totale"], ["familial","total service"]),
        "hospitality_profile": K(["carne asada","ranch entertaining"], ["carne asada","ranch entertaining"]),
        "cta_psychology":      K(["agendar cita"], ["book a visit"]),
        "visual_rhythm":       K(["aperto","scenografico"], ["open","scenic"]),
        "design_culture":      K(["San Pedro","Valle Oriente","Sierra Madre"], ["San Pedro","Valle Oriente","Sierra Madre"]),
        "seo_behavior":        K(["interiorista Monterrey"], ["Monterrey interior designer"]),
        "publishing_windows":  K(["set-nov","feb-apr"], ["Sep-Nov","Feb-Apr"]),
    },
    {
        "code": "latam_bogota", "macro_market_code": "spanish_latam", "country_code": "CO",
        "region_type": "metro", "locale_code": "es-ES", "sort_order": 840,
        "display_name": {"it-IT": "Bogotá", "en-US": "Bogotá"},
        "editorial_profile":   K(["colto","sobrio","artigianale"], ["cultured","restrained","artisanal"]),
        "luxury_profile":      K(["heritage coloniale","altezza","Andes"], ["colonial heritage","altitude","Andes"]),
        "consultation_style":  K(["formale","famigliare"], ["formal","familial"]),
        "visual_behavior":     K(["mattoni","colonial heritage","montagne"], ["brick","colonial heritage","mountains"]),
        "decision_rhythm":     K(["riflessivo","famigliare"], ["reflective","familial"]),
        "relationship_expectation": K(["discrezione","artigianato"], ["discretion","craft"]),
        "hospitality_profile": K(["almuerzo largo","art collection"], ["long lunch","art collection"]),
        "cta_psychology":      K(["agendar cita"], ["book a visit"]),
        "visual_rhythm":       K(["denso","editoriale"], ["dense","editorial"]),
        "design_culture":      K(["Chicó","Rosales","Usaquén"], ["Chicó","Rosales","Usaquén"]),
        "seo_behavior":        K(["interiorista Bogotá"], ["Bogotá interior designer"]),
        "publishing_windows":  K(["mar-mag","ago-ott"], ["Mar-May","Aug-Oct"]),
    },
    {
        "code": "latam_buenos_aires", "macro_market_code": "spanish_latam", "country_code": "AR",
        "region_type": "metro", "locale_code": "es-ES", "sort_order": 850,
        "display_name": {"it-IT": "Buenos Aires", "en-US": "Buenos Aires"},
        "editorial_profile":   K(["europeo","colto","heritage"], ["European","cultured","heritage"]),
        "luxury_profile":      K(["palacete","Recoleta","heritage francese"], ["palacete","Recoleta","French heritage"]),
        "consultation_style":  K(["formale","accademico"], ["formal","academic"]),
        "visual_behavior":     K(["palacetes","heritage francese","Avenida"], ["palacetes","French heritage","Avenida"]),
        "decision_rhythm":     K(["riflessivo","heritage"], ["reflective","heritage"]),
        "relationship_expectation": K(["heritage rispettato","colto"], ["heritage respected","cultured"]),
        "hospitality_profile": K(["cena tardía","milonga culture"], ["late dinner","milonga culture"]),
        "cta_psychology":      K(["agendar cita"], ["book a visit"]),
        "visual_rhythm":       K(["denso","editoriale"], ["dense","editorial"]),
        "design_culture":      K(["Recoleta","Palermo","San Isidro"], ["Recoleta","Palermo","San Isidro"]),
        "seo_behavior":        K(["interiorista Buenos Aires"], ["Buenos Aires interior designer"]),
        "publishing_windows":  K(["mar-mag","ago-nov"], ["Mar-May","Aug-Nov"]),
    },
    {
        "code": "latam_santiago", "macro_market_code": "spanish_latam", "country_code": "CL",
        "region_type": "metro", "locale_code": "es-ES", "sort_order": 860,
        "display_name": {"it-IT": "Santiago", "en-US": "Santiago"},
        "editorial_profile":   K(["sobrio","contemporaneo","misurato"], ["restrained","contemporary","measured"]),
        "luxury_profile":      K(["Andes","modernismo","vigneti"], ["Andes","modernism","vineyards"]),
        "consultation_style":  K(["formale","pragmatico"], ["formal","pragmatic"]),
        "visual_behavior":     K(["montagne","pietra","minimalismo"], ["mountains","stone","minimalism"]),
        "decision_rhythm":     K(["pragmatico","riflessivo"], ["pragmatic","reflective"]),
        "relationship_expectation": K(["discrezione","sostenibilità"], ["discretion","sustainability"]),
        "hospitality_profile": K(["asado","wine country"], ["asado","wine country"]),
        "cta_psychology":      K(["agendar cita"], ["book a visit"]),
        "visual_rhythm":       K(["sobrio","calmo"], ["restrained","calm"]),
        "design_culture":      K(["Las Condes","Vitacura","Lo Barnechea"], ["Las Condes","Vitacura","Lo Barnechea"]),
        "seo_behavior":        K(["interiorista Santiago"], ["Santiago interior designer"]),
        "publishing_windows":  K(["mar-mag","set-nov"], ["Mar-May","Sep-Nov"]),
    },
]


def main():
    url = os.environ["DATABASE_URL"]
    conn = psycopg2.connect(url)
    cur = conn.cursor()
    n = 0
    for sm in SUBMARKETS:
        # Build the SQL columns dynamically
        cols = list(sm.keys())
        cols.append("updated_at")
        vals = [sm[k] if not isinstance(sm[k], (dict, list)) else json.dumps(sm[k], ensure_ascii=False) for k in sm.keys()]
        vals.append("NOW()")

        placeholders = ", ".join([f"%s::jsonb" if isinstance(sm[k], (dict, list)) else "%s" for k in sm.keys()])
        placeholders += ", NOW()"

        set_clause = ", ".join([
            f"{k} = EXCLUDED.{k}" for k in sm.keys() if k != "code"
        ] + ["updated_at = NOW()"])

        sql = f"""
            INSERT INTO market_submarkets ({", ".join(cols)})
            VALUES ({placeholders})
            ON CONFLICT (code) DO UPDATE SET {set_clause}
        """
        cur.execute(sql, vals[:-1])  # drop trailing NOW() literal — it's already in placeholders
        n += 1
        print(f"  [ok] {sm['code']:30s} → {sm['display_name'].get('en-US')}")
    conn.commit()
    cur.close()
    conn.close()
    print(f"\nSeeded {n} submarkets")


if __name__ == "__main__":
    main()
