"""Phase P0.3.A — Deep validation pass (testing agent T1).

Goes beyond the baseline regression. Confirms:
  • Fresh ingest with a DIFFERENT image URL still produces a complete
    interpretation (pipeline reliability under variation).
  • EN_AE reading uses culturally-native UAE prestige vocabulary.
  • DE_DE reading is in German and uses architectural rigor language.
  • EN_AE and DE_DE are NOT translations of each other (distinct prose,
    distinct word stems).
  • All interpretation fields are populated and market_fit_score ∈ [0,100].
  • Timeline integration: when a reference is ingested with project_id,
    GET /api/projects/{pid}/timeline shows a reference.added event with
    a human label — and NO AI/technical language leaks.
"""
import os
import re
import pytest
import requests

BASE = os.environ.get("REACT_APP_BACKEND_URL", "").rstrip("/")
assert BASE, "REACT_APP_BACKEND_URL must be set"

SUPER_EMAIL = "demo@moodfordesign.com"
SUPER_PASS = "Blueprint2024!"

# DIFFERENT image URL than the baseline test suite (which uses photo-1600585154340-be6161a56a0c)
FRESH_IMG_URL = "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0"
PROJECT_ID = "adea95da-3ff8-4a10-80db-bbc02a0ed119"


def _login(email, password):
    s = requests.Session()
    r = s.post(f"{BASE}/api/auth/login",
               json={"email": email, "password": password}, timeout=20)
    assert r.status_code == 200, f"login failed: {r.status_code} {r.text[:200]}"
    body = r.json()
    sess = body.get("session") or {}
    token = sess.get("access_token") or body.get("access_token") or body.get("token")
    assert token, "no token in login response"
    s.headers.update({"Authorization": f"Bearer {token}"})
    return s


@pytest.fixture(scope="module")
def super_admin():
    return _login(SUPER_EMAIL, SUPER_PASS)


# ─── Forbidden language: must never appear in any user-facing prose ──────
# Per spec: AI must be invisible. Curator voice only.
AI_LEAK_PATTERNS = [
    r"\bAI\b",
    r"artificial intelligence",
    r"generated by",
    r"model name",
    r"language model",
    r"computer vision",
    r"\bGPT[- ]?",
    r"\bclaude\b",
    r"\bLLM\b",
    r"machine learning",
]


def _has_ai_leak(text: str) -> list:
    found = []
    if not text:
        return found
    for pat in AI_LEAK_PATTERNS:
        if re.search(pat, text, re.IGNORECASE):
            found.append(pat)
    return found


# ─── Fresh ingest with a different image URL ─────────────────────────────

class TestFreshIngestVariation:
    def test_fresh_ingest_en_ae_full_pipeline(self, super_admin):
        r = super_admin.post(f"{BASE}/api/references", timeout=120, json={
            "imported_image_url": FRESH_IMG_URL,
            "source_type": "curator_pick",
            "source_url": "https://example.com/fresh-villa",
            "curator_name": "Stefano Ogrisek",
            "locale_code": "EN_AE",
            "design_intent": "Penthouse on the Palm, prestige register",
            "project_id": PROJECT_ID,
        })
        assert r.status_code == 201, r.text[:500]
        body = r.json()
        assert body.get("ok") is True
        ref = body["reference"]

        assert ref["imported_image_url"] == FRESH_IMG_URL
        assert ref["project_id"] == PROJECT_ID
        TestFreshIngestVariation.ref_id = ref["id"]

        interps = ref.get("interpretations") or []
        if ref["editorial_status"] != "ready":
            # Fail-closed: LLM unreachable → status stays at processing,
            # NO interpretation row, NO timeline event. This is spec-correct
            # ("NO RAW IMPORTS"). We assert the gating contract here, then skip.
            assert ref["editorial_status"] == "processing_editorial_reading"
            assert interps == [], "no interpretation row when LLM failed"
            # GET list (default ?status=ready) must NOT leak this ref
            lst = super_admin.get(f"{BASE}/api/references", timeout=15).json()
            ids = {r["id"] for r in lst.get("references", [])}
            assert ref["id"] not in ids, "RAW IMPORT LEAKED into ready list"
            pytest.skip(
                "EMERGENT_LLM_KEY budget appears exhausted — pipeline "
                "correctly fail-closed (status=processing, no interp row, "
                "not listed). Re-run after budget reset."
            )

        # Reference promoted to ready (no raw imports leak)
        assert ref["editorial_status"] == "ready"
        assert len(interps) >= 1, "interpretation must exist when status=ready"
        en = interps[0]

        # All fields populated
        for fld in ("atmosphere", "material_language", "hospitality_level",
                    "architectural_tone", "emotional_positioning",
                    "editorial_reading"):
            v = en.get(fld)
            assert isinstance(v, str) and len(v.strip()) > 0, \
                f"interpretation field '{fld}' must be non-empty, got: {v!r}"

        # market_fit_score bounded
        score = en.get("market_fit_score")
        assert score is not None, "market_fit_score must be present"
        assert 0 <= score <= 100, f"score out of bounds: {score}"

        # Locale tagged correctly
        assert en["locale"] == "EN_AE"

        # AI invisibility — no leaks in editorial prose
        for fld in ("atmosphere", "material_language", "editorial_reading",
                    "emotional_positioning"):
            leaks = _has_ai_leak(en.get(fld) or "")
            assert not leaks, f"AI leak in {fld}: {leaks} :: {en.get(fld)[:160]}"

        # Stash for downstream tests
        TestFreshIngestVariation.ref_id = ref["id"]
        TestFreshIngestVariation.en_reading = en["editorial_reading"]
        TestFreshIngestVariation.en_atmosphere = en["atmosphere"]


# ─── EN_AE vs DE_DE: NATIVE reinterpretation, NOT translation ───────────

class TestCulturalDistinctness:
    def test_regenerate_de_de_is_german_and_distinct(self, super_admin):
        ref_id = getattr(TestFreshIngestVariation, "ref_id", None)
        if not ref_id:
            pytest.skip("fresh ingest skipped — no ref_id available")
        r = super_admin.post(
            f"{BASE}/api/references/{ref_id}/interpretations",
            timeout=120, json={"locale_code": "DE_DE"},
        )
        if r.status_code == 503:
            pytest.skip("LLM unreachable (likely budget) — endpoint correctly returns 503")
        assert r.status_code == 200, r.text[:500]
        de = r.json()["interpretation"]
        assert de["locale"] == "DE_DE"

        de_reading = (de.get("editorial_reading") or "")
        assert len(de_reading) > 60, "DE reading too short"

        # Must read as German: at least one German stop-word / function-word
        # cluster present. We avoid asserting any single token (LLM-resilient).
        german_cues = re.findall(
            r"\b(?:und|der|die|das|ist|mit|von|für|eine|einer|nicht|sich|"
            r"konstrukt|architektonisch|materialität|disziplin|haltung|"
            r"präzision|rigor|klarheit|raum|ruhe|schwere)\w*\b",
            de_reading, re.IGNORECASE,
        )
        assert len(german_cues) >= 2, \
            f"DE_DE reading does not read as German. Found cues={german_cues}; reading={de_reading[:300]}"

        # AI invisibility
        for fld in ("atmosphere", "material_language", "editorial_reading",
                    "emotional_positioning"):
            leaks = _has_ai_leak(de.get(fld) or "")
            assert not leaks, f"AI leak in DE.{fld}: {leaks}"

        # NOT a translation of EN — compare token Jaccard on stems
        def tokens(s: str) -> set:
            return set(re.findall(r"[a-zA-ZäöüÄÖÜß]{5,}", s.lower()))
        en_tokens = tokens(TestFreshIngestVariation.en_reading)
        de_tokens = tokens(de_reading)
        if en_tokens and de_tokens:
            overlap = len(en_tokens & de_tokens) / len(en_tokens | de_tokens)
            assert overlap < 0.35, \
                f"EN_AE and DE_DE readings overlap too much ({overlap:.2f}) — looks like a translation, not native reinterpretation"

    def test_en_ae_uses_uae_prestige_register(self, super_admin):
        """EN_AE reading should reference UAE prestige / Gulf hospitality
        register at least sometimes. We do a soft check on a small lexicon
        across BOTH atmosphere and editorial_reading."""
        ref_id = getattr(TestFreshIngestVariation, "ref_id", None)
        if not ref_id:
            pytest.skip("fresh ingest skipped — no ref_id available")
        r = super_admin.get(f"{BASE}/api/references/{ref_id}", timeout=15)
        assert r.status_code == 200
        interps = r.json()["reference"]["interpretations"]
        en = next((i for i in interps if i["locale"] == "EN_AE"), None)
        if en is None:
            pytest.skip("EN_AE interpretation absent — LLM call did not complete")
        haystack = " ".join(filter(None, [
            en.get("atmosphere"), en.get("hospitality_level"),
            en.get("emotional_positioning"), en.get("editorial_reading"),
        ])).lower()
        # We allow ANY of these registers — LLM-resilient.
        uae_cues = ("majlis", "gulf", "emirate", "palm", "uae", "dubai",
                    "abu dhabi", "prestige", "hospitality", "welcome",
                    "discreet", "private", "patron", "client", "discretion",
                    "luxury", "tactile", "sensorial")
        hits = [c for c in uae_cues if c in haystack]
        # We want at least 1 cultural anchor — LLMs vary, so 1 is the floor.
        assert hits, \
            f"EN_AE reading shows no UAE/prestige cultural anchor. Haystack: {haystack[:400]}"


# ─── Timeline integration with project_id ─────────────────────────────────

class TestTimelineIntegration:
    def test_timeline_shows_reference_added_event(self, super_admin):
        r = super_admin.get(
            f"{BASE}/api/projects/{PROJECT_ID}/timeline", timeout=20)
        assert r.status_code == 200, r.text[:300]
        body = r.json()
        # Endpoint may return {"events":[...]} or {"timeline":[...]} — be permissive
        events = body.get("events") or body.get("timeline") or body
        if isinstance(events, dict):
            events = events.get("items") or []
        assert isinstance(events, list) and events, "timeline returned no events"

        ref_events = [e for e in events
                      if (e.get("event") or "").startswith("reference.")
                      or e.get("ref_id") == getattr(TestFreshIngestVariation, "ref_id", "__none__")]
        if not ref_events:
            pytest.skip(
                "No reference.* events on this project timeline yet. If the "
                "fresh ingest was skipped due to LLM budget exhaustion, no "
                "timeline event is expected (spec: events only fire when "
                "interpretation lands)."
            )

        # The reference.added event must point at our fresh ref
        our_event = next((e for e in ref_events
                          if e.get("ref_id") == getattr(TestFreshIngestVariation, "ref_id", None)), None)
        if our_event is None:
            pytest.skip("fresh ingest produced no interpretation → no timeline event (spec-correct)")

        # Title must be human-readable and have NO AI/technical leaks
        title = our_event.get("title") or ""
        assert title, "timeline event has no human title"
        assert len(title) >= 5

        for e in ref_events:
            t = e.get("title") or ""
            leaks = _has_ai_leak(t)
            assert not leaks, \
                f"AI/technical leak in timeline title: {leaks} :: {t}"
