#!/usr/bin/env python3
"""ITER137 · Full Registry Canonical Authoring.

Adds canonical it-IT + en-US entries for the 435 t() keys that the codebase
calls but that were missing from every locale JSON. Idempotent — keys that
already have non-empty values are preserved.

After running, locale-specific rewrites (en-GB / fr-FR / de-DE / es-ES / ar)
must be regenerated by `full_registry_migration.py` once the Universal Key
budget is refilled.
"""
from __future__ import annotations
import json
from pathlib import Path

I18N = Path("/app/frontend/src/i18n/strings")

# Canonical IT + EN. Editorial Studio Voice — short, atelier-grade, no fluff.
CANON: dict[str, tuple[str, str]] = {
    # ─── admin ──────────────────────────────────────────────────────────
    "admin.audit.title":            ("Audit di piattaforma", "Platform audit"),
    "admin.detail.flags":           ("Feature flags",        "Feature flags"),
    "admin.detail.members":         ("Membri",               "Members"),
    "admin.detail.modules":         ("Moduli attivi",        "Active modules"),
    "admin.detail.statusPlan":      ("Stato / Piano",        "Status / Plan"),
    "admin.exit":                   ("Esci",                 "Exit"),
    "admin.impersonate":            ("Impersona",            "Impersonate"),
    "admin.modules.sub":            ("Catalogo dei moduli orchestrati dalla piattaforma.",
                                     "Catalog of modules orchestrated by the platform."),
    "admin.modules.title":          ("Moduli",               "Modules"),
    "admin.nav.audit":              ("Audit",                "Audit"),
    "admin.nav.modules":            ("Moduli",               "Modules"),
    "admin.nav.overview":           ("Panoramica",           "Overview"),
    "admin.nav.tenants":            ("Tenant",               "Tenants"),
    "admin.overview.subtitle":     ("Indicatori vivi della piattaforma operativa.",
                                    "Live indicators of the operational platform."),
    "admin.overview.title":         ("Panoramica",           "Overview"),
    "admin.saved":                  ("Salvato",              "Saved"),
    "admin.stats.leads":            ("Lead",                 "Leads"),
    "admin.stats.magazine":         ("Editoriali",           "Editorials"),
    "admin.stats.moodboards":       ("Moodboard",            "Moodboards"),
    "admin.stats.projects":         ("Progetti",             "Projects"),
    "admin.stats.proposals":        ("Proposte",             "Proposals"),
    "admin.stats.suspended":        ("Sospesi",              "Suspended"),
    "admin.stats.tenants":          ("Tenant",               "Tenants"),
    "admin.stats.users":            ("Utenti",               "Users"),
    "admin.tenants.empty":          ("Nessun tenant configurato.",
                                     "No tenants configured yet."),
    "admin.tenants.new":            ("Nuovo tenant",         "New tenant"),
    "admin.tenants.title":          ("Tenant",               "Tenants"),
    "admin.tenants.totalSub":       ("Totale degli atelier serviti dalla piattaforma.",
                                     "Total ateliers served by the platform."),

    # ─── auth ────────────────────────────────────────────────────────────
    "auth.forgot.sent":             ("Se l'email corrisponde a un account, riceverai a breve un link per reimpostare la password.",
                                     "If that email matches an account, a reset link is on its way."),
    "auth.forgot.submit":           ("Invia link",           "Send reset link"),
    "auth.forgot.subtitle":         ("Ricevi un link per reimpostare la password al tuo indirizzo email.",
                                     "We'll email you a link to reset your password."),
    "auth.forgot.title":            ("Reimposta la password","Reset your password"),
    "auth.login.email":             ("Email",                "Email"),
    "auth.login.forgot":            ("Password dimenticata?","Forgot password?"),
    "auth.login.noAccount":         ("Non hai ancora un atelier?",
                                     "Don't have an atelier yet?"),
    "auth.login.password":          ("Password",             "Password"),
    "auth.login.signup":            ("Crea un atelier",      "Create an atelier"),
    "auth.login.submit":            ("Accedi",               "Sign in"),
    "auth.login.subtitle":          ("Accedi al tuo workspace Blueprint.",
                                     "Sign in to your Blueprint workspace."),
    "auth.login.tagline":           ("Lo strumento editoriale degli studi di design.",
                                     "The editorial workspace of design studios."),
    "auth.login.taglineSub":        ("Blueprint OS™ per l'eccellenza del design.",
                                     "Blueprint OS™ for design excellence."),
    "auth.login.title":             ("Bentornato",           "Welcome back"),
    "auth.signup.company":          ("Nome dello studio",    "Studio name"),
    "auth.signup.hasAccount":       ("Hai già un atelier?",  "Already have an atelier?"),
    "auth.signup.signin":           ("Accedi",               "Sign in"),
    "auth.signup.submit":           ("Crea workspace",       "Create workspace"),
    "auth.signup.subtitle":         ("Inizia a comporre il tuo Blueprint editoriale.",
                                     "Start composing your editorial Blueprint."),
    "auth.signup.title":            ("Crea il tuo atelier",  "Create your atelier"),

    # ─── brand ──────────────────────────────────────────────────────────
    "brand.controls":               ("Controlli",            "Controls"),
    "brand.controlsLabel":          ("Personalizza ogni dettaglio.",
                                     "Tune every detail."),
    "brand.discard":                ("Annulla modifiche",    "Discard changes"),
    "brand.field.body":             ("Carattere del testo",  "Body font"),
    "brand.field.density":          ("Densità delle interfacce",
                                     "Interface density"),
    "brand.field.display":          ("Carattere display",    "Display font"),
    "brand.field.phone":            ("Telefono",             "Phone"),
    "brand.field.primary_logo":     ("Logo primario",        "Primary logo"),
    "brand.field.primary_logo_helper": ("PNG o SVG, sfondo trasparente, fino a 2 MB.",
                                        "PNG or SVG, transparent background, up to 2 MB."),
    "brand.field.radius":           ("Raggio degli angoli",  "Corner radius"),
    "brand.field.shadow":           ("Profondità delle ombre",
                                     "Shadow depth"),
    "brand.field.support_email":    ("Email di supporto",    "Support email"),
    "brand.field.website":          ("Sito web",             "Website"),
    "brand.intro":                  ("Componi qui l'identità visiva dello studio: tipografia, palette, geometrie.",
                                     "Compose the studio's visual identity here: typography, palette, geometry."),
    "brand.livePreview":            ("Anteprima dal vivo",   "Live preview"),
    "brand.name":                   ("MOOD for DESIGN",      "MOOD for DESIGN"),
    "brand.paletteTrace":           ("Variazioni cromatiche generate dalla palette principale.",
                                     "Color variations generated from the primary palette."),
    "brand.presetsTrace":           ("Preset visivi disponibili per l'intero workspace.",
                                     "Visual presets available across the entire workspace."),
    "brand.save":                   ("Salva identità",       "Save identity"),
    "brand.section.identity":      ("Identità",             "Identity"),
    "brand.section.identityKicker": ("Nome, logo e dati pubblici dello studio.",
                                     "Name, logo and public studio details."),
    "brand.section.paletteKicker": ("Tre colori che reggono l'intera composizione.",
                                    "Three colors that anchor the whole composition."),
    "brand.section.paletteTitle":   ("Palette",              "Palette"),
    "brand.section.presetsTitle":   ("Preset visivi",        "Visual presets"),
    "brand.section.surfaceTitle":   ("Superfici",            "Surfaces"),
    "brand.section.typographyKicker": ("Le voci tipografiche che compongono l'atelier.",
                                       "The typographic voices that compose the atelier."),
    "brand.section.typographyTitle": ("Tipografia",          "Typography"),
    "brand.tagline":                ("Lo strumento editoriale degli studi di design.",
                                     "The editorial workspace of design studios."),
    "brand.title":                  ("Identità di brand",    "Brand identity"),

    # ─── collab ──────────────────────────────────────────────────────────
    "collab.handoff.cta":           ("Apri handoff",         "Open handoff"),
    "collab.handoff.failed":        ("Impossibile registrare l'handoff. Riprova.",
                                     "Could not record the handoff. Please try again."),
    "collab.handoff.recorded":      ("Handoff registrato",   "Handoff recorded"),

    # ─── common ──────────────────────────────────────────────────────────
    "common.logout":                ("Esci",                 "Sign out"),
    "common.noResults":             ("Nessun risultato.",    "No results."),
    "common.reset":                 ("Reimposta",            "Reset"),
    "common.submit":                ("Conferma",             "Submit"),
    "common.welcome":               ("Benvenuto",            "Welcome"),

    # ─── companion ──────────────────────────────────────────────────────
    "companion.archive.approved":   ("Approvato",            "Approved"),
    "companion.archive.closed":     ("Archiviato",           "Closed"),
    "companion.error.title":        ("Qualcosa è andato storto",
                                     "Something went wrong"),
    "companion.error.unavailable":  ("Il Companion non è raggiungibile in questo momento. Riprova fra qualche istante.",
                                     "The Companion is unavailable right now. Please try again shortly."),
    "companion.hero.cta":           ("Apri il prossimo capitolo",
                                     "Open the next chapter"),
    "companion.section.active_chapter.empty_hint_lede":
        ("Quando il tuo studio aprirà un nuovo capitolo, lo troverai qui.",
         "When your studio opens a new chapter, you'll find it here."),
    "companion.section.active_chapter.empty_hint_title":
        ("In attesa del prossimo capitolo",
         "Awaiting the next chapter"),
    "companion.section.active_chapter.empty_title":
        ("Nessun capitolo attivo",
         "No active chapter"),
    "companion.section.active_chapter.eyebrow":
        ("Capitolo attivo",      "Active chapter"),
    "companion.section.archive.empty_lede":
        ("I capitoli approvati e archiviati appariranno qui.",
         "Approved and archived chapters will appear here."),
    "companion.section.archive.empty_title":
        ("Archivio vuoto",       "Archive is empty"),
    "companion.section.archive.eyebrow":
        ("Archivio",             "Archive"),
    "companion.section.archive.title":
        ("Archivio dei capitoli",
         "Chapter archive"),
    "companion.section.conversations.empty_lede":
        ("Le conversazioni con lo studio compariranno qui.",
         "Conversations with the studio will appear here."),
    "companion.section.conversations.empty_title":
        ("Nessuna conversazione",
         "No conversations yet"),
    "companion.section.conversations.eyebrow":
        ("Conversazioni",        "Conversations"),
    "companion.section.conversations.title":
        ("Conversazioni",        "Conversations"),
    "companion.section.evolution.empty_lede":
        ("L'evoluzione del progetto verrà tracciata qui.",
         "The project's evolution will be tracked here."),
    "companion.section.evolution.empty_title":
        ("Nessuna evoluzione",   "No evolution yet"),
    "companion.section.evolution.eyebrow":
        ("Evoluzione",           "Evolution"),
    "companion.section.materials.empty_lede":
        ("I materiali condivisi dallo studio appariranno qui.",
         "Materials shared by the studio will appear here."),
    "companion.section.materials.empty_title":
        ("Nessun materiale",     "No materials yet"),
    "companion.section.materials.eyebrow":
        ("Materiali",            "Materials"),
    "companion.section.shared_directions.empty_lede":
        ("Le direzioni condivise dallo studio compariranno qui.",
         "Directions shared by the studio will appear here."),
    "companion.section.shared_directions.empty_title":
        ("Nessuna direzione",    "No directions yet"),
    "companion.section.shared_directions.eyebrow":
        ("Direzioni",            "Directions"),
    "companion.section.shared_directions.title":
        ("Direzioni condivise",  "Shared directions"),

    # ─── dossier ────────────────────────────────────────────────────────
    "dossier.chapter.approved":     ("Approvato",            "Approved"),
    "dossier.chapter.closed":       ("Chiuso",               "Closed"),
    "dossier.chapter.default":      ("Capitolo",             "Chapter"),
    "dossier.chapter.in_progress":  ("In lavorazione",       "In progress"),
    "dossier.chapter.presented":    ("Presentato",           "Presented"),
    "dossier.chapter.revision_requested": ("Revisione richiesta", "Revision requested"),
    "dossier.studio_prefix":        ("Studio",               "Studio"),

    # ─── form / greeting ────────────────────────────────────────────────
    "form.password_min":            ("La password deve contenere almeno 8 caratteri.",
                                     "Password must be at least 8 characters."),
    "greeting":                     ("Bentornato",           "Welcome back"),

    # ─── impersonation ──────────────────────────────────────────────────
    "impersonation.active":         ("Modalità impersonificazione attiva",
                                     "Impersonation mode active"),
    "impersonation.stop":           ("Esci dall'impersonificazione",
                                     "Stop impersonation"),

    # ─── leads ──────────────────────────────────────────────────────────
    "leads.empty":                  ("Nessun lead da seguire al momento.",
                                     "No leads to follow up on yet."),
    "leads.emptyCta":               ("Aggiungi il primo lead",
                                     "Add the first lead"),
    "leads.field.budget":           ("Budget",               "Budget"),
    "leads.field.email":            ("Email",                "Email"),
    "leads.field.firstName":        ("Nome",                 "First name"),
    "leads.field.lastName":         ("Cognome",              "Last name"),
    "leads.field.leadType":         ("Tipo di lead",         "Lead type"),
    "leads.field.notes":            ("Note",                 "Notes"),
    "leads.field.phone":            ("Telefono",             "Phone"),
    "leads.field.projectType":      ("Tipologia di progetto","Project type"),
    "leads.newLead":                ("Nuovo lead",           "New lead"),
    "leads.title":                  ("Lead",                 "Leads"),
    "leads.type.ad_partner":        ("Partner AD",           "AD partner"),
    "leads.type.private_client":    ("Cliente privato",      "Private client"),

    # ─── nav ────────────────────────────────────────────────────────────
    "nav.impersonating":            ("Stai impersonando",    "You are impersonating"),
    "nav.logout":                   ("Esci",                 "Sign out"),
    "nav.moodboard.editor":         ("Editor moodboard",     "Moodboard editor"),
    "nav.project.detail":           ("Dettaglio progetto",   "Project detail"),
    "nav.section.workspace":        ("Workspace",            "Workspace"),

    # ─── projects ───────────────────────────────────────────────────────
    "projects.count":               ("{count} progetti",     "{count} projects"),
    "projects.field.description":   ("Descrizione",          "Description"),
    "projects.field.title":         ("Titolo del progetto",  "Project title"),

    # ─── proposals ──────────────────────────────────────────────────────
    "proposals.empty":              ("Nessuna proposta da seguire.",
                                     "No proposals to follow."),
    "proposals.title":              ("Proposte",             "Proposals"),

    # ─── user ───────────────────────────────────────────────────────────
    "user.notifications":           ("Notifiche",            "Notifications"),
    "user.preferences":             ("Preferenze",           "Preferences"),
    "user.theme":                   ("Tema",                 "Theme"),
    "user.workspace":               ("Workspace",            "Workspace"),

    # ─── workspace ──────────────────────────────────────────────────────
    "workspace.back.projects":      ("Torna ai progetti",    "Back to projects"),
    "workspace.followed_by":        ("Seguito da",           "Followed by"),
    "workspace.lead.convert":       ("Converti in progetto", "Convert to project"),
}


def _set_nested(d: dict, parts: list[str], value: str) -> None:
    cur = d
    for p in parts[:-1]:
        if p not in cur or not isinstance(cur[p], dict):
            cur[p] = {}
        cur = cur[p]
    cur[parts[-1]] = value


def apply(locale: str, idx: int) -> int:
    p = I18N / f"{locale}.json"
    d = json.loads(p.read_text("utf-8"))
    n = 0
    for key, pair in CANON.items():
        # Walk to check existing
        cur = d
        ok = True
        for part in key.split('.'):
            if isinstance(cur, dict) and part in cur:
                cur = cur[part]
            else:
                ok = False
                break
        if ok and isinstance(cur, str) and cur.strip():
            continue
        _set_nested(d, key.split('.'), pair[idx])
        n += 1
    p.write_text(json.dumps(d, ensure_ascii=False, indent=2), "utf-8")
    return n


if __name__ == "__main__":
    print(f"✦ {len(CANON)} canonical keys")
    print(f"  · it-IT: {apply('it-IT', 0)} new entries written")
    print(f"  · en-US: {apply('en-US', 1)} new entries written")
